import { useState, useEffect } from "react";

/* ══════ GRAMMAR ══════ */
const G=[
{c:"Zamanlar (Tenses)",u:[
{t:"Present Continuous",s:"Şimdiki Zaman (am/is/are + Ving)",e:"Şu anda olan, geçici ve değişen durumlar için. Durum fiilleri (know, like, want) ile kullanılmaz.",st:[{l:"(+)",f:"Sub + am/is/are + Ving",x:"She is working now.",r:"Şu an çalışıyor."},{l:"(−)",f:"Sub + am/is/are not + Ving",x:"I'm not sleeping.",r:"Uyumuyorum."},{l:"(?)",f:"Am/Is/Are + Sub + Ving?",x:"Are you coming?",r:"Geliyor musun?"}],x:[{e:"I'm reading a good book.",t:"İyi bir kitap okuyorum."},{e:"Kate is learning Italian.",t:"Kate İtalyanca öğreniyor."},{e:"The world is changing fast.",t:"Dünya hızla değişiyor."},{e:"You're working hard today.",t:"Bugün çok çalışıyorsun."},{e:"Is your English getting better?",t:"İngilizcen gelişiyor mu?"},{e:"I'm staying with friends this week.",t:"Bu hafta arkadaşlarda kalıyorum."}],ti:["know/like/want/believe → continuous yapılmaz","today/this week/this year ile geçici durumlar","getting/becoming/increasing → değişim"],w:[{e:"at the moment",t:"şu anda"},{e:"right now",t:"şu an"},{e:"currently",t:"hâlihazırda"},{e:"these days",t:"bu aralar"},{e:"still",t:"hâlâ"},{e:"Look!/Listen!",t:"Bak!/Dinle!"}]},

{t:"Present Simple",s:"Geniş Zaman (V1 / Vs)",e:"Genel gerçekler, alışkanlıklar, tekrarlayan eylemler. He/she/it → fiile -s eklenir. Sıklık zarfları fiilden önce gelir.",st:[{l:"(+)",f:"Sub + V1 (he/she → Vs)",x:"She works in a bank.",r:"Bankada çalışır."},{l:"(−)",f:"Sub + don't/doesn't + V1",x:"I don't drink coffee.",r:"Kahve içmem."},{l:"(?)",f:"Do/Does + Sub + V1?",x:"Do you speak English?",r:"İngilizce konuşur musun?"}],x:[{e:"Water boils at 100 degrees.",t:"Su 100 derecede kaynar."},{e:"I usually get up at 7.",t:"Genellikle 7'de kalkarım."},{e:"She doesn't eat meat.",t:"Et yemez."},{e:"How often do you exercise?",t:"Ne sıklıkta spor yaparsın?"},{e:"The sun rises in the east.",t:"Güneş doğudan doğar."},{e:"He always arrives late.",t:"Her zaman geç gelir."}],ti:["always > usually > often > sometimes > rarely > never","3. tekil: works, goes, watches, studies, tries","do/does'dan sonra fiil yalın kalır"],w:[{e:"always",t:"her zaman"},{e:"usually",t:"genellikle"},{e:"often",t:"sıklıkla"},{e:"sometimes",t:"bazen"},{e:"rarely/seldom",t:"nadiren"},{e:"never",t:"asla"},{e:"every day/week",t:"her gün/hafta"},{e:"once/twice a week",t:"haftada bir/iki kez"}]},

{t:"Past Simple",s:"Geçmiş Zaman (-dı/-di)",e:"Geçmişte belirli zamanda biten eylemler. Regular: +ed (worked). Irregular: go→went, see→saw, eat→ate, buy→bought, take→took, make→made, come→came, give→gave, know→knew, write→wrote, speak→spoke, break→broke, drive→drove, choose→chose, forget→forgot, wear→wore, lose→lost, find→found, think→thought, bring→brought, teach→taught, catch→caught, feel→felt, keep→kept, leave→left, meet→met, pay→paid, sell→sold, send→sent, sit→sat, stand→stood, win→won.",st:[{l:"(+)",f:"Sub + V2",x:"I worked yesterday.",r:"Dün çalıştım."},{l:"(−)",f:"Sub + didn't + V1",x:"She didn't go.",r:"Gitmedi."},{l:"(?)",f:"Did + Sub + V1?",x:"Did you see it?",r:"Gördün mü?"}],x:[{e:"Mozart was born in 1756.",t:"Mozart 1756'da doğdu."},{e:"We didn't have a holiday last year.",t:"Geçen yıl tatil yapmadık."},{e:"I got up early and had breakfast.",t:"Erken kalktım, kahvaltı yaptım."},{e:"Where did you go?",t:"Nereye gittin?"},{e:"It was cold so we stayed inside.",t:"Soğuktu, içeride kaldık."}],ti:["yesterday, last week, ago, in 2020","was→I/he/she/it, were→you/we/they","Düzensiz fiilleri ezberle!"],w:[{e:"yesterday",t:"dün"},{e:"last week/month/year",t:"geçen hafta/ay/yıl"},{e:"ago (two days ago)",t:"önce"},{e:"in the past",t:"geçmişte"},{e:"when I was young",t:"gençken"},{e:"in 1990",t:"1990'da"}]},

{t:"Past Continuous",s:"Geçmiş Sürekli (-yordu)",e:"Geçmişte belirli anda devam eden eylem. was/were + Ving. Kullanım: a) Belirli anda devam b) İki paralel eylem (while) c) Kesilen eylem (when + V2) d) always ile sinir bozucu alışkanlık. Non-action verbs kullanılmaz!",st:[{l:"(+)",f:"Sub + was/were + Ving",x:"I was studying at 9pm.",r:"Akşam 9'da çalışıyordum."},{l:"(−)",f:"Sub + wasn't/weren't + Ving",x:"They weren't listening.",r:"Dinlemiyorlardı."},{l:"(?)",f:"Was/Were + Sub + Ving?",x:"Were you sleeping?",r:"Uyuyor muydun?"}],x:[{e:"I was cooking while she was reading.",t:"O okurken ben yemek yapıyordum."},{e:"I was walking when it started to rain.",t:"Yürüyordum, yağmur başladı."},{e:"He was always losing his keys.",t:"Hep anahtarlarını kaybediyordu."},{e:"What were you doing at 7pm?",t:"Akşam 7'de ne yapıyordun?"}],ti:["while/as → iki uzun eylem aynı anda","when → kısa eylem uzun eylemi keser","Non-action verbs kullanılmaz (know, believe)"],w:[{e:"while/as",t:"...iken"},{e:"when",t:"...diğinde"},{e:"at this time yesterday",t:"dün bu saatte"},{e:"all day/morning",t:"bütün gün/sabah"}]},

{t:"Present Perfect Simple",s:"have/has + V3",e:"Geçmişte belirsiz zamanda olan, şimdiye bağlantısı olan eylemler. 1) Sonuç: I've lost my key (şu an yok). 2) Deneyim: I've been to Paris. 3) just/already/yet. 4) for/since ile süre.\n\nhave been to = gidip döndü\nhave gone to = gitti, hâlâ orada\nhave been in = süredir orada",st:[{l:"(+)",f:"Sub + have/has + V3",x:"I have lost my key.",r:"Anahtarımı kaybettim."},{l:"(−)",f:"Sub + haven't/hasn't + V3",x:"She hasn't arrived yet.",r:"Henüz gelmedi."},{l:"(?)",f:"Have/Has + Sub + V3?",x:"Have you ever been to Japan?",r:"Hiç Japonya'ya gittin mi?"}],x:[{e:"I've just had lunch.",t:"Az önce yedim."},{e:"Have you already finished?",t:"Çoktan bitirdin mi?"},{e:"I've been to London three times.",t:"Londra'ya 3 kez gittim."},{e:"Tom has gone to Egypt.",t:"Tom Mısır'a gitti (hâlâ orada)."},{e:"This is the best film I've ever seen.",t:"Bu gördüğüm en iyi film."},{e:"I've lived here for 5 years.",t:"5 yıldır burada yaşıyorum."}],ti:["just/already/yet → eylemin kendisi","ever/never → hayat deneyimleri","for (süre) / since (başlangıç) → süre odaklı"],w:[{e:"just",t:"az önce"},{e:"already",t:"çoktan"},{e:"yet",t:"henüz"},{e:"ever",t:"hiç"},{e:"never",t:"asla"},{e:"so far",t:"şimdiye kadar"},{e:"recently/lately",t:"son zamanlarda"},{e:"for",t:"...dır (süre)"},{e:"since",t:"...den beri"},{e:"once/twice",t:"bir/iki kez"},{e:"many times",t:"birçok kez"},{e:"before",t:"daha önce"}]},

{t:"Present Perfect Continuous",s:"have/has been + Ving",e:"Geçmişte başlayıp devam eden eylemin SÜRESİNİ vurgular. Simple → SONUÇ: He has written 1000 stories. Continuous → SÜRE: He has been writing since 2010. How many? → Simple. How long? → Continuous.",st:[{l:"(+)",f:"Sub + have/has been + Ving",x:"I've been teaching for 20 years.",r:"20 yıldır öğretiyorum."},{l:"(?)",f:"How long have/has Sub been Ving?",x:"How long have you been waiting?",r:"Ne zamandır bekliyorsun?"}],x:[{e:"I've been living here for 2 years.",t:"2 yıldır burada yaşıyorum."},{e:"She's been studying since morning.",t:"Sabahtan beri çalışıyor."},{e:"It's been raining all day.",t:"Bütün gün yağmur yağıyor."},{e:"You look tired. Have you been working hard?",t:"Yorgun görünüyorsun. Çok mu çalıştın?"}],ti:["for → süre, since → başlangıç noktası","How many → Simple, How long → Continuous"],w:[{e:"for + süre",t:"...dır"},{e:"since + başlangıç",t:"...den beri"},{e:"all day/week/year",t:"bütün gün/hafta/yıl"},{e:"How long?",t:"Ne zamandır?"}]},

{t:"Past Perfect",s:"had + V3",e:"Geçmişteki bir olaydan DAHA ÖNCE olan olay. 'Geçmişin geçmişi.' When I arrived, the film had already started. (Film zaten başlamıştı.)",st:[{l:"(+)",f:"Sub + had + V3",x:"She had already left when I called.",r:"Aradığımda çoktan gitmişti."},{l:"(−)",f:"Sub + hadn't + V3",x:"I hadn't seen the film before.",r:"Filmi daha önce görmemiştim."}],x:[{e:"When I arrived, the meeting had started.",t:"Vardığımda toplantı başlamıştı."},{e:"She had never flown before.",t:"Daha önce hiç uçmamıştı."},{e:"I'd eaten so I wasn't hungry.",t:"Yemiştim, aç değildim."}],ti:["İki geçmiş olaydan ÖNCEKİ için kullanılır","already, just, never, before ile sık kullanılır"],w:[{e:"had + V3",t:"...mıştı"},{e:"already",t:"çoktan"},{e:"by the time",t:"...zamana kadar"},{e:"after",t:"...den sonra"},{e:"before",t:"...den önce"}]},

{t:"Used to / Would",s:"Geçmiş Alışkanlıklar (-ırdı)",e:"used to → hem eylem hem durum fiilleriyle. would → SADECE eylem fiilleriyle. I used to have a car ✓ I would have a car ✗",st:[{l:"used to (+)",f:"Sub + used to + V1",x:"I used to play tennis.",r:"Eskiden tenis oynardım."},{l:"used to (−)",f:"Sub + didn't use to + V1",x:"I didn't use to like coffee.",r:"Kahve sevmezdim."},{l:"would (+)",f:"Sub + would + V1",x:"I would go running.",r:"Koşuya giderdim."}],x:[{e:"I used to smoke but I quit.",t:"Eskiden sigara içerdim, bıraktım."},{e:"This building used to be a cinema.",t:"Bu bina eskiden sinemaydi."},{e:"We would play in the garden every day.",t:"Her gün bahçede oynardık."}],ti:["used to → artık yapmadığın şeyler","would → sadece eylem fiilleri, durum fiilleri yok","be used to (alışkın) ile karıştırma!"],w:[{e:"used to",t:"eskiden ...ırdı"},{e:"would (past habit)",t:"...ırdı (sadece eylem)"}]}
]},

{c:"Gelecek Zaman",u:[
{t:"Will / Going to",s:"Gelecek Zaman",e:"WILL → anlık karar, tahmin, söz verme, teklif. GOING TO → önceden planlanmış, kanıta dayalı tahmin. Will you...? → rica. I'll → anlık karar. I'm going to → plan.",st:[{l:"will (+)",f:"Sub + will + V1",x:"I'll help you.",r:"Sana yardım edeceğim."},{l:"going to (+)",f:"Sub + am/is/are going to + V1",x:"I'm going to study medicine.",r:"Tıp okuyacağım."},{l:"will (?)",f:"Will + Sub + V1?",x:"Will you marry me?",r:"Benimle evlenir misin?"}],x:[{e:"I'll have the chicken, please. (instant decision)",t:"Tavuk alayım lütfen."},{e:"I'm going to visit my parents tomorrow. (plan)",t:"Yarın ailemi ziyaret edeceğim."},{e:"Look at those clouds! It's going to rain. (evidence)",t:"Şu bulutlara bak! Yağmur yağacak."},{e:"I promise I won't tell anyone.",t:"Kimseye söylemeyeceğime söz veriyorum."}],ti:["will → anlık karar/tahmin/söz, going to → plan/kanıt","Shall I/we...? → teklif/öneri","won't = will not"],w:[{e:"will",t:"...ecek (anlık)"},{e:"going to",t:"...ecek (planlı)"},{e:"shall",t:"...eyim mi?"},{e:"probably",t:"muhtemelen"},{e:"definitely",t:"kesinlikle"},{e:"promise",t:"söz vermek"}]},

{t:"Time Clauses (Gelecek)",s:"when/until/as soon as/before/after",e:"Gelecek zaman cümlelerinde zaman bağlacından sonra will KULLANILMAZ → Present Simple kullanılır. I'll call you when I arrive. ✓ I'll call you when I will arrive. ✗",st:[{l:"Kalıp",f:"will + V ... when/until/after/before + Present Simple",x:"I'll call when I arrive.",r:"Vardığımda arayacağım."}],x:[{e:"I'll wait until you come back.",t:"Sen dönene kadar bekleyeceğim."},{e:"As soon as it stops raining, we'll go out.",t:"Yağmur diner dinmez çıkacağız."},{e:"I'll finish this before I go to bed.",t:"Yatmadan önce bunu bitireceğim."}],ti:["when, until, as soon as, by the time, after, before → Present Simple","will zaman bağlacından sonra KULLANILMAZ"],w:[{e:"when",t:"...diğinde"},{e:"until",t:"...e kadar"},{e:"as soon as",t:"...yapar yapmaz"},{e:"by the time",t:"...zamana kadar"},{e:"after",t:"...den sonra"},{e:"before",t:"...den önce"}]}
]},

{c:"Modal Fiiller",u:[
{t:"Must / Have to / Need to",s:"Zorunluluk ve Gereklilik",e:"MUST → içsel zorunluluk, mantıksal çıkarım, güçlü tavsiye. mustn't → YASAK. HAVE TO → dışsal zorunluluk (kural/yasa). don't have to → zorunluluk YOK. NEED TO → gereklilik (daha hafif). HAD TO → geçmiş zorunluluk.",st:[{l:"must",f:"Sub + must + V1",x:"I must study tonight.",r:"Bu gece çalışmalıyım."},{l:"mustn't",f:"Sub + mustn't + V1",x:"You mustn't smoke here.",r:"Burada sigara içme!"},{l:"have to",f:"Sub + have/has to + V1",x:"I have to wear a uniform.",r:"Üniforma giymek zorundayım."},{l:"don't have to",f:"Sub + don't have to + V1",x:"You don't have to come.",r:"Gelmek zorunda değilsin."}],x:[{e:"You must be tired! (logical deduction)",t:"Çok yorgun olmalısın!"},{e:"I don't have to work on Saturdays.",t:"Cumartesi çalışmak zorunda değilim."},{e:"I had to take a taxi.",t:"Taksi almak zorunda kaldım."},{e:"I need to study for my exams.",t:"Sınavlara çalışmam gerekiyor."}],ti:["mustn't = YASAK ≠ don't have to = GEREK YOK","must'ın geçmişi yok → had to"],w:[{e:"must",t:"-meli (içsel)"},{e:"mustn't",t:"yasak"},{e:"have to",t:"zorunda (dışsal)"},{e:"don't have to",t:"zorunda değil"},{e:"need to",t:"gerekiyor"},{e:"needn't",t:"gerekmez"},{e:"had to",t:"zorunda kaldı"}]},

{t:"Can / Could / Be able to",s:"Yetenek ve İzin",e:"CAN → şu anki yetenek, izin. COULD → geçmiş genel yetenek. was able to → belirli durumda başarı. Can I...? → izin. Could you...? → rica.",st:[{l:"can",f:"Sub + can + V1",x:"I can swim.",r:"Yüzebilirim."},{l:"could",f:"Sub + could + V1",x:"I could read at 4.",r:"4 yaşında okuyabiliyordum."},{l:"be able to",f:"Sub + was able to + V1",x:"She was able to escape.",r:"Kaçmayı başardı."}],x:[{e:"Can you speak French?",t:"Fransızca konuşabilir misin?"},{e:"Can I use your phone?",t:"Telefonunu kullanabilir miyim?"},{e:"Could you help me?",t:"Bana yardım eder misiniz?"},{e:"That can't be true!",t:"Bu doğru olamaz!"}],ti:["could → genel yetenek, was able to → belirli başarı"],w:[{e:"can",t:"...ebilir"},{e:"could",t:"...ebilirdi"},{e:"be able to",t:"yapabilmek"},{e:"can't",t:"...emez"}]},

{t:"Should / Had better",s:"Tavsiye",e:"SHOULD → tavsiye, doğru olan. HAD BETTER → daha güçlü uyarı (yapmazsan kötü olur).",st:[{l:"should",f:"Sub + should + V1",x:"You should see a doctor.",r:"Doktora gitmelisin."},{l:"had better",f:"Sub + 'd better + V1",x:"You'd better hurry.",r:"Acele etsen iyi olur."}],x:[{e:"You should eat more vegetables.",t:"Daha çok sebze yemelisin."},{e:"You'd better take an umbrella.",t:"Şemsiye alsan iyi olur."},{e:"We'd better not be late.",t:"Geç kalmamamız iyi olur."}],ti:["should → genel tavsiye, had better → uyarı"],w:[{e:"should",t:"-meli (tavsiye)"},{e:"shouldn't",t:"-memeli"},{e:"had better",t:"...se iyi olur"},{e:"had better not",t:"...memesi iyi olur"}]},

{t:"May / Might",s:"Olasılık",e:"MAY → olabilir (%50). MIGHT → belki (%30-40, daha düşük). may/might not → olmayabilir.",st:[{l:"may/might",f:"Sub + may/might + V1",x:"It may/might rain.",r:"Yağmur yağabilir."}],x:[{e:"I may go to the party.",t:"Partiye gidebilirim."},{e:"She might not come.",t:"Gelmeyebilir."},{e:"Take an umbrella. It might rain.",t:"Şemsiye al. Yağabilir."}],ti:["may → biraz daha olası, might → daha düşük ihtimal","May I...? → kibarca izin isteme"],w:[{e:"may",t:"olabilir"},{e:"might",t:"belki, olabilir"},{e:"may not",t:"olmayabilir"},{e:"perhaps/maybe",t:"belki"}]}
]},

{c:"Şart Cümleleri",u:[
{t:"Conditionals (Type 0-1-2-3)",s:"If Clauses / Şart Cümleleri",e:"TYPE 0 → Bilimsel gerçek (%100): If+Present, Present\nTYPE 1 → Olası gelecek: If+Present, will+V\nTYPE 2 → Hayali/düşük ihtimal: If+Past, would+V\nTYPE 3 → Geçmişte olmamış: If+Past Perfect, would have+V3\n\nI wish / If only → keşke",st:[{l:"Type 0",f:"If + Present, Present",x:"If you heat ice, it melts.",r:"Buzu ısıtırsan erir."},{l:"Type 1",f:"If + Present, will + V",x:"If it rains, I'll stay home.",r:"Yağarsa evde kalırım."},{l:"Type 2",f:"If + Past, would + V",x:"If I had money, I'd travel.",r:"Param olsa seyahat ederdim."},{l:"Type 3",f:"If + Past Perfect, would have + V3",x:"If I had studied, I would have passed.",r:"Çalışsaydım geçerdim."}],x:[{e:"If you mix red and yellow, you get orange.",t:"Kırmızı sarıyı karıştırırsan turuncu olur."},{e:"If I go to England, I'll visit my teacher.",t:"İngiltere'ye gidersem öğretmenimi ziyaret edeceğim."},{e:"If I were you, I would apologize.",t:"Senin yerinde olsam özür dilerdim."},{e:"If I had known, I would have helped.",t:"Bilseydim yardım ederdim."},{e:"I wish I had more time.",t:"Keşke daha çok zamanım olsa."},{e:"I wish I hadn't said that.",t:"Keşke onu söylemeseydim."}],ti:["Type 2: If I were (was değil) tercih edilir","Type 3: pişmanlık ifade eder","unless = if not, as long as = ...dığı sürece"],w:[{e:"if",t:"eğer"},{e:"unless",t:"...mazsa"},{e:"as long as",t:"...dığı sürece"},{e:"provided that",t:"...şartıyla"},{e:"I wish / If only",t:"keşke"},{e:"even if",t:"...olsa bile"}]}
]},

{c:"Edilgen Çatı & Dolaylı Anlatım",u:[
{t:"Passive Voice",s:"Edilgen Çatı (be + V3)",e:"Eylemi yapan değil, yapılan önemli olduğunda. Present: is/are+V3. Past: was/were+V3. Perfect: has been+V3. Future: will be+V3. Modal: can/must be+V3.",st:[{l:"Present",f:"Sub + is/are + V3",x:"English is spoken here.",r:"Burada İngilizce konuşulur."},{l:"Past",f:"Sub + was/were + V3",x:"The car was stolen.",r:"Araba çalındı."},{l:"Perfect",f:"Sub + has been + V3",x:"The email has been sent.",r:"E-posta gönderildi."},{l:"Future",f:"Sub + will be + V3",x:"It will be finished tomorrow.",r:"Yarın bitirilecek."}],x:[{e:"This house was built in 1960.",t:"Bu ev 1960'ta yapıldı."},{e:"My car is being repaired.",t:"Arabam tamir ediliyor."},{e:"The meeting will be held on Friday.",t:"Toplantı Cuma yapılacak."}],ti:["by + yapan: The book was written by Orwell","get + V3 (informal): He got fired."],w:[{e:"is done",t:"yapılır"},{e:"was done",t:"yapıldı"},{e:"has been done",t:"yapılmış"},{e:"will be done",t:"yapılacak"},{e:"being done",t:"yapılıyor"},{e:"by",t:"tarafından"}]},

{t:"Reported Speech",s:"Dolaylı Anlatım",e:"Birinin söylediğini aktarırken zaman bir adım geriye kayar. Present→Past, Past→Past Perfect, will→would, can→could.",st:[{l:"Kalıp",f:"He said (that) + bir adım geri",x:"He said he was tired.",r:"Yorgun olduğunu söyledi."}],x:[{e:"I am tired → He said he was tired.",t:"Yorgunum → Yorgun olduğunu söyledi."},{e:"I will help → She said she would help.",t:"Yardım edeceğim → Yardım edeceğini söyledi."},{e:"I can swim → He said he could swim.",t:"Yüzebilirim → Yüzebildiğini söyledi."}],ti:["Zaman kayması: am/is→was, are→were, have→had, will→would","Yer/zaman da değişir: here→there, today→that day, tomorrow→the next day"],w:[{e:"said",t:"dedi"},{e:"told me",t:"bana söyledi"},{e:"asked",t:"sordu"},{e:"that (optional)",t:"...dığını"}]}
]},

{c:"Sıfat Cümlecikleri & Bağlaçlar",u:[
{t:"Relative Clauses",s:"who/which/that/whose/where",e:"İsmi tanımlayan yan cümlecik. who→insanlar, which→nesneler, that→hepsi, whose→sahiplik, where→yer, when→zaman.",st:[{l:"who",f:"noun + who + verb",x:"The woman who lives next door is a doctor.",r:"Yan komşu kadın doktor."},{l:"which",f:"noun + which + verb",x:"The book which I bought is great.",r:"Aldığım kitap harika."},{l:"whose",f:"noun + whose + noun",x:"The man whose car broke down called help.",r:"Arabası bozulan adam yardım çağırdı."}],x:[{e:"I know someone who speaks 5 languages.",t:"5 dil konuşan birini tanıyorum."},{e:"The hotel where we stayed was excellent.",t:"Kaldığımız otel mükemmeldi."},{e:"The film (that) we saw was great.",t:"İzlediğimiz film harikaydı."}],ti:["Nesne konumundaki that atılabilir","which → virgüllü ekstra bilgi cümlecikleri"],w:[{e:"who",t:"...olan (insanlar)"},{e:"which",t:"...olan (nesneler)"},{e:"that",t:"...olan (hepsi)"},{e:"whose",t:"...nın (sahiplik)"},{e:"where",t:"...de (yer)"},{e:"when",t:"...de (zaman)"}]},

{t:"Although / Despite / In spite of",s:"Zıtlık Bağlaçları",e:"although/though/even though + cümle: ...olmasına rağmen. despite/in spite of + isim/-ing: ...e rağmen. however → ancak, bununla birlikte.",st:[{l:"although",f:"Although + clause, main clause",x:"Although it rained, we went out.",r:"Yağmur yağmasına rağmen çıktık."},{l:"despite",f:"Despite + noun/-ing, main clause",x:"Despite the rain, we went out.",r:"Yağmura rağmen çıktık."}],x:[{e:"Even though I was tired, I couldn't sleep.",t:"Yorgun olmama rağmen uyuyamadım."},{e:"In spite of being rich, he's unhappy.",t:"Zengin olmasına rağmen mutsuz."}],ti:["although/though + CÜMLE, despite/in spite of + İSİM veya -ING"],w:[{e:"although/though",t:"...olmasına rağmen"},{e:"even though",t:"...olsa bile"},{e:"despite",t:"...e rağmen (+isim)"},{e:"in spite of",t:"...e rağmen (+isim)"},{e:"however",t:"ancak"},{e:"whereas",t:"oysa"}]}
]},

{c:"Phrasal Verbs & Edatlar",u:[
{t:"Phrasal Verbs",s:"Öbeksi Fiiller (25+)",e:"Fiil + edat = yeni anlam. Separable: Turn off the TV / Turn the TV off. Inseparable: Look after ✓ Zamir ortaya girer: Turn it off ✓, Turn off it ✗",st:[],x:[{e:"Get up at 7 every morning.",t:"Her sabah 7'de kalk."},{e:"Can you turn off the music?",t:"Müziği kapat."},{e:"Don't give up! Keep trying.",t:"Vazgeçme! Dene."},{e:"I need to find out what happened.",t:"Ne olduğunu öğrenmeliyim."},{e:"We ran out of milk.",t:"Sütümüz bitti."},{e:"She looks after her mother.",t:"Annesine bakıyor."}],ti:["Zamir separable'da ORTAYA girer: Turn it off ✓","Anlamları ezberle — kelime kelime çeviri yanlış olur"],w:[{e:"get up",t:"kalkmak"},{e:"turn on/off",t:"açmak/kapatmak"},{e:"turn up/down",t:"sesi açmak/kısmak"},{e:"look forward to",t:"dört gözle beklemek"},{e:"look after",t:"bakmak"},{e:"look up to",t:"saygı duymak"},{e:"pick up",t:"almak, toplamak"},{e:"give up",t:"vazgeçmek"},{e:"find out",t:"öğrenmek"},{e:"take off",t:"çıkarmak/kalkmak"},{e:"put on",t:"giymek/takmak"},{e:"break down",t:"bozulmak"},{e:"go on",t:"devam etmek"},{e:"come back",t:"geri dönmek"},{e:"run out of",t:"tükenmek"},{e:"get on with",t:"geçinmek"},{e:"set up",t:"kurmak"},{e:"carry on",t:"devam etmek"},{e:"work out",t:"çözmek/spor yapmak"},{e:"fill in",t:"doldurmak (form)"},{e:"plug in",t:"prize takmak"},{e:"print out",t:"çıktı almak"},{e:"shut down",t:"kapanmak"},{e:"log in/out",t:"giriş/çıkış"},{e:"go away",t:"uzaklaşmak"},{e:"throw away",t:"atmak"},{e:"put off",t:"ertelemek"},{e:"bring up",t:"yetiştirmek/konu açmak"},{e:"take up",t:"başlamak (hobi)"},{e:"make up",t:"uydurmak/barışmak"}]},

{t:"Prepositions of Place & Time",s:"Yer ve Zaman Edatları",e:"TIME: at → saat/özel gün (at 7, at night, at Christmas). in → ay/yıl/mevsim/uzun süre (in May, in 2020, in summer, in the morning). on → gün/tarih (on Monday, on 5th May, on my birthday).\n\nPLACE: in → içinde (in the room, in London). at → belirli nokta (at the bus stop, at home). on → yüzeyde (on the table, on the wall).",st:[],x:[{e:"I'll meet you at 3 o'clock.",t:"Saat 3'te buluşalım."},{e:"She was born in 1990.",t:"1990'da doğdu."},{e:"The meeting is on Friday.",t:"Toplantı Cuma."},{e:"The book is on the table.",t:"Kitap masanın üstünde."},{e:"I live in Istanbul.",t:"İstanbul'da yaşıyorum."},{e:"I'll see you at the airport.",t:"Havalimanında görüşürüz."}],ti:["at night, at the weekend, at Christmas","in the morning/afternoon/evening","on Monday, on my birthday"],w:[{e:"in",t:"içinde / -de (ay/yıl)"},{e:"on",t:"üstünde / -de (gün)"},{e:"at",t:"-de (saat/nokta)"},{e:"between",t:"arasında"},{e:"in front of",t:"önünde"},{e:"behind",t:"arkasında"},{e:"under",t:"altında"},{e:"above/over",t:"üstünde/üzerinde"},{e:"next to/beside",t:"yanında"},{e:"opposite",t:"karşısında"},{e:"through",t:"içinden"},{e:"along",t:"boyunca"},{e:"across",t:"karşısına"},{e:"into",t:"içine"},{e:"out of",t:"dışına"},{e:"towards",t:"...e doğru"},{e:"past",t:"yanından geçerek"}]}
]}
];

/* ══════ VOCABULARY ══════ */
const V=[
{c:"Dünya ve Doğa",u:[
{t:"Weather",s:"Hava Durumu",e:"sun→sunny, cloud→cloudy, fog→foggy, wind→windy, rain→rainy, snow→snowy, ice→icy. heavy rain=şiddetli, light rain=hafif, strong wind=şiddetli, thick fog=yoğun.",st:[],x:[{e:"It poured with rain this afternoon.",t:"Bardaktan boşanırcasına yağdı."},{e:"We had heavy rain at the weekend.",t:"Hafta sonunda şiddetli yağmur yağdı."},{e:"The sun came out after lunch.",t:"Öğleden sonra güneş açtı."}],ti:["pour with rain = şakır şakır yağmak","humid = nemli, chilly = serin"],w:[{e:"sunny",t:"güneşli"},{e:"cloudy",t:"bulutlu"},{e:"foggy",t:"sisli"},{e:"windy",t:"rüzgarlı"},{e:"snowy",t:"karlı"},{e:"icy",t:"buzlu"},{e:"rainy/wet",t:"yağmurlu"},{e:"clear sky",t:"açık gökyüzü"},{e:"pour with rain",t:"şakır şakır yağmak"},{e:"shower",t:"sağanak"},{e:"storm",t:"fırtına"},{e:"thunderstorm",t:"gök gürültülü fırtına"},{e:"thunder",t:"gök gürültüsü"},{e:"lightning",t:"şimşek"},{e:"humid",t:"nemli"},{e:"boiling",t:"çok sıcak"},{e:"warm",t:"ılık"},{e:"chilly/cool",t:"serin"},{e:"freezing",t:"dondurucu"},{e:"below zero",t:"sıfırın altında"},{e:"temperature",t:"sıcaklık"},{e:"degrees",t:"derece"},{e:"forecast",t:"tahmin"},{e:"climate",t:"iklim"},{e:"drought",t:"kuraklık"},{e:"flood",t:"sel"},{e:"blizzard",t:"kar fırtınası"},{e:"heatwave",t:"sıcak dalgası"},{e:"tornado",t:"hortum"},{e:"earthquake",t:"deprem"}]},
{t:"Animals",s:"Hayvanlar ve Böcekler",e:"Wild animals, farm animals, insects and sea creatures.",st:[],x:[{e:"A whale is the largest mammal.",t:"Balina en büyük memeli."},{e:"Bees make honey.",t:"Arılar bal yapar."}],ti:["mammal=memeli, reptile=sürüngen, insect=böcek"],w:[{e:"whale",t:"balina"},{e:"shark",t:"köpekbalığı"},{e:"dolphin",t:"yunus"},{e:"elephant",t:"fil"},{e:"tiger",t:"kaplan"},{e:"lion",t:"aslan"},{e:"bear",t:"ayı"},{e:"wolf",t:"kurt"},{e:"deer",t:"geyik"},{e:"monkey",t:"maymun"},{e:"snake",t:"yılan"},{e:"eagle",t:"kartal"},{e:"penguin",t:"penguen"},{e:"cow",t:"inek"},{e:"sheep",t:"koyun"},{e:"goat",t:"keçi"},{e:"horse",t:"at"},{e:"chicken",t:"tavuk"},{e:"pig",t:"domuz"},{e:"donkey",t:"eşek"},{e:"camel",t:"deve"},{e:"rabbit",t:"tavşan"},{e:"bee",t:"arı"},{e:"butterfly",t:"kelebek"},{e:"mosquito",t:"sivrisinek"},{e:"ant",t:"karınca"},{e:"spider",t:"örümcek"},{e:"fly",t:"sinek"}]},
{t:"Physical World",s:"Fiziksel Dünya",e:"Coğrafya terimleri: dağ, nehir, okyanus, kıta vb.",st:[],x:[{e:"The Amazon is the largest rainforest.",t:"Amazon en büyük yağmur ormanı."}],ti:["continent=kıta, ocean=okyanus"],w:[{e:"mountain",t:"dağ"},{e:"hill",t:"tepe"},{e:"valley",t:"vadi"},{e:"river",t:"nehir"},{e:"lake",t:"göl"},{e:"ocean/sea",t:"okyanus/deniz"},{e:"island",t:"ada"},{e:"peninsula",t:"yarımada"},{e:"continent",t:"kıta"},{e:"desert",t:"çöl"},{e:"forest/jungle",t:"orman"},{e:"rainforest",t:"yağmur ormanı"},{e:"waterfall",t:"şelale"},{e:"cave",t:"mağara"},{e:"cliff",t:"uçurum"},{e:"coast",t:"kıyı"},{e:"beach",t:"kumsal"},{e:"landscape",t:"manzara"},{e:"volcano",t:"yanardağ"},{e:"earthquake",t:"deprem"}]}
]},

{c:"İnsanlar",u:[
{t:"Body and Movement",s:"Vücut ve Hareket",e:"Vücut bölümleri ve hareket fiilleri.",st:[],x:[{e:"She nodded her head.",t:"Başını salladı."},{e:"He shrugged his shoulders.",t:"Omuzlarını silkti."}],ti:["nod=başla onaylamak, shake head=hayır demek"],w:[{e:"head",t:"baş/kafa"},{e:"face",t:"yüz"},{e:"hair",t:"saç"},{e:"forehead",t:"alın"},{e:"eyebrow",t:"kaş"},{e:"eyelash",t:"kirpik"},{e:"cheek",t:"yanak"},{e:"chin",t:"çene"},{e:"neck",t:"boyun"},{e:"shoulder",t:"omuz"},{e:"chest",t:"göğüs"},{e:"back",t:"sırt"},{e:"arm",t:"kol"},{e:"elbow",t:"dirsek"},{e:"wrist",t:"bilek"},{e:"hand",t:"el"},{e:"finger",t:"parmak"},{e:"thumb",t:"baş parmak"},{e:"waist",t:"bel"},{e:"hip",t:"kalça"},{e:"knee",t:"diz"},{e:"ankle",t:"ayak bileği"},{e:"toe",t:"ayak parmağı"},{e:"skin",t:"cilt/deri"},{e:"bone",t:"kemik"},{e:"muscle",t:"kas"},{e:"blood",t:"kan"},{e:"heart",t:"kalp"},{e:"brain",t:"beyin"},{e:"lung",t:"akciğer"},{e:"stomach/liver",t:"mide/karaciğer"},{e:"nod",t:"baş sallamak"},{e:"shake",t:"sallamak"},{e:"wave",t:"el sallamak"},{e:"point",t:"işaret etmek"},{e:"bend",t:"eğilmek"},{e:"stretch",t:"germek/uzanmak"},{e:"yawn",t:"esnemek"}]},
{t:"Appearance",s:"Dış Görünüş",e:"Birinin görünüşünü tanımlama: boy, kilo, saç, yüz.",st:[],x:[{e:"She's quite tall with long dark hair.",t:"Uzun boylu, koyu uzun saçlı."},{e:"He's medium height and well-built.",t:"Orta boylu ve yapılı."}],ti:["good-looking/attractive=yakışıklı/çekici, plain=sıradan görünüşlü"],w:[{e:"tall/short",t:"uzun/kısa"},{e:"medium height",t:"orta boy"},{e:"slim/thin",t:"ince/zayıf"},{e:"well-built",t:"yapılı"},{e:"overweight",t:"kilolu"},{e:"good-looking",t:"yakışıklı/güzel"},{e:"attractive",t:"çekici"},{e:"pretty",t:"güzel (kadın)"},{e:"handsome",t:"yakışıklı (erkek)"},{e:"straight hair",t:"düz saç"},{e:"curly hair",t:"kıvırcık saç"},{e:"wavy hair",t:"dalgalı saç"},{e:"blonde/fair",t:"sarışın"},{e:"dark",t:"koyu"},{e:"bald",t:"kel"},{e:"beard",t:"sakal"},{e:"moustache",t:"bıyık"},{e:"freckles",t:"çil"},{e:"pale",t:"solgun"},{e:"tanned",t:"bronz"}]},
{t:"Character",s:"Karakter Özellikleri",e:"Olumlu ve olumsuz karakter sıfatları. Ön eklerle olumsuz yapma: un-, im-, in-, dis-.",st:[],x:[{e:"She's very kind and generous.",t:"Çok nazik ve cömert."},{e:"He can be a bit mean sometimes.",t:"Bazen biraz cimri olabiliyor."}],ti:["kind↔unkind, patient↔impatient, honest↔dishonest"],w:[{e:"kind/unkind",t:"nazik/kaba"},{e:"generous/mean",t:"cömert/cimri"},{e:"friendly/unfriendly",t:"cana yakın/soğuk"},{e:"honest/dishonest",t:"dürüst/sahtekar"},{e:"patient/impatient",t:"sabırlı/sabırsız"},{e:"polite/rude",t:"kibar/kaba"},{e:"calm/nervous",t:"sakin/gergin"},{e:"sensible/silly",t:"mantıklı/aptalca"},{e:"hard-working/lazy",t:"çalışkan/tembel"},{e:"brave/cowardly",t:"cesur/korkak"},{e:"cheerful/miserable",t:"neşeli/mutsuz"},{e:"confident/shy",t:"kendine güvenen/utangaç"},{e:"ambitious",t:"hırslı"},{e:"stubborn",t:"inatçı"},{e:"reliable",t:"güvenilir"},{e:"selfish",t:"bencil"},{e:"thoughtful",t:"düşünceli"}]},
{t:"Feelings",s:"Duygular",e:"anger→angry, anxiety→anxious, pride→proud, curiosity→curious. mood=ruh hali, emotion=duygu.",st:[],x:[{e:"I feel anxious about the exam.",t:"Sınav için kaygılıyım."},{e:"She was upset when she heard.",t:"Duyunca üzüldü."}],ti:["mood = ruh hali, stressed = stresli"],w:[{e:"happy/cheerful",t:"mutlu/neşeli"},{e:"sad/miserable",t:"üzgün/perişan"},{e:"angry",t:"kızgın"},{e:"anxious/worried",t:"kaygılı"},{e:"scared/frightened",t:"korkmuş"},{e:"jealous",t:"kıskanç"},{e:"proud",t:"gururlu"},{e:"disappointed",t:"hayal kırıklığı"},{e:"confused",t:"kafası karışık"},{e:"upset",t:"üzgün"},{e:"depressed",t:"bunalımlı"},{e:"curious",t:"meraklı"},{e:"bored",t:"sıkılmış"},{e:"excited",t:"heyecanlı"},{e:"nervous",t:"gergin"},{e:"embarrassed",t:"utanmış"},{e:"lonely",t:"yalnız"},{e:"grateful",t:"minnettar"},{e:"guilty",t:"suçlu hisseden"},{e:"relieved",t:"rahatlamış"},{e:"stressed",t:"stresli"},{e:"mood",t:"ruh hali"},{e:"emotion",t:"duygu"}]},
{t:"Family and Friends",s:"Aile ve Arkadaşlık",e:"ex-=eski, -in-law=evlilik akrabalığı, step-=üvey, half-=yarım kardeş. get on well with=iyi geçinmek.",st:[],x:[{e:"We're a close family.",t:"Yakın bir aileyiz."},{e:"I get on well with my uncle.",t:"Amcamla iyi geçinirim."}],ti:["Thomas's wife deyin, the wife of Thomas değil"],w:[{e:"parents",t:"anne baba"},{e:"husband/wife",t:"koca/karı"},{e:"son/daughter",t:"oğul/kız"},{e:"brother/sister",t:"erkek/kız kardeş"},{e:"grandfather/mother",t:"dede/nine"},{e:"grandchildren",t:"torunlar"},{e:"uncle/aunt",t:"amca-dayı/hala-teyze"},{e:"cousin",t:"kuzen"},{e:"nephew/niece",t:"yeğen (e/k)"},{e:"widow/widower",t:"dul (k/e)"},{e:"twins",t:"ikizler"},{e:"only child",t:"tek çocuk"},{e:"elder/younger",t:"büyük/küçük"},{e:"stepfather",t:"üvey baba"},{e:"half-brother",t:"üvey kardeş"},{e:"mother-in-law",t:"kayınvalide"},{e:"father-in-law",t:"kayınpeder"},{e:"brother-in-law",t:"kayınbirader"},{e:"sister-in-law",t:"baldız/yenge"},{e:"son-in-law",t:"damat"},{e:"daughter-in-law",t:"gelin"},{e:"ex-husband",t:"eski koca"},{e:"best friend",t:"en iyi arkadaş"},{e:"mate",t:"arkadaş"},{e:"friendship",t:"arkadaşlık"},{e:"relationship",t:"ilişki"},{e:"get on well with",t:"iyi geçinmek"},{e:"get to know",t:"tanışmak"},{e:"close family",t:"yakın aile"},{e:"remarry",t:"tekrar evlenmek"}]}
]},

{c:"Günlük Yaşam",u:[
{t:"Daily Routines",s:"Günlük Rutinler",e:"have breakfast/lunch/dinner, have a shower, do the housework/shopping/washing-up, go to work/school, get dressed, wake up.",st:[],x:[{e:"I usually have breakfast at 7:30.",t:"Genelde 7:30'da kahvaltı yaparım."},{e:"She does the housework in the morning.",t:"Ev işlerini sabah yapar."}],ti:["have + meal: have breakfast, have lunch","do + iş: do homework, do the washing-up","go + aktivite: go shopping, go swimming"],w:[{e:"wake up",t:"uyanmak"},{e:"get up",t:"kalkmak"},{e:"have a shower/bath",t:"duş/banyo yapmak"},{e:"get dressed",t:"giyinmek"},{e:"have breakfast",t:"kahvaltı yapmak"},{e:"go to work/school",t:"işe/okula gitmek"},{e:"have lunch",t:"öğle yemeği"},{e:"get home",t:"eve varmak"},{e:"have dinner",t:"akşam yemeği"},{e:"do the housework",t:"ev işi yapmak"},{e:"do the shopping",t:"alışveriş yapmak"},{e:"do the washing-up",t:"bulaşık yıkamak"},{e:"do the ironing",t:"ütü yapmak"},{e:"do the cooking",t:"yemek yapmak"},{e:"go to bed",t:"yatmak"},{e:"fall asleep",t:"uykuya dalmak"},{e:"oversleep",t:"uyuyakalmak"},{e:"set the alarm",t:"alarm kurmak"},{e:"commute",t:"işe gidip gelmek"}]},
{t:"Health",s:"Sağlık",e:"Hastalıklar, belirtiler ve tedavi.",st:[],x:[{e:"I've got a terrible headache.",t:"Korkunç bir baş ağrım var."},{e:"She had a cold last week.",t:"Geçen hafta nezle oldu."}],ti:["have a cold/headache/temperature","feel sick/dizzy/faint","go to the doctor/hospital"],w:[{e:"headache",t:"baş ağrısı"},{e:"stomachache",t:"karın ağrısı"},{e:"backache",t:"sırt ağrısı"},{e:"toothache",t:"diş ağrısı"},{e:"sore throat",t:"boğaz ağrısı"},{e:"cold",t:"soğuk algınlığı"},{e:"flu",t:"grip"},{e:"cough",t:"öksürük"},{e:"fever/temperature",t:"ateş"},{e:"pain",t:"ağrı"},{e:"allergy",t:"alerji"},{e:"infection",t:"enfeksiyon"},{e:"injury",t:"yaralanma"},{e:"prescription",t:"reçete"},{e:"medicine/pill",t:"ilaç/hap"},{e:"chemist/pharmacy",t:"eczane"},{e:"bandage",t:"bandaj"},{e:"operation",t:"ameliyat"},{e:"check-up",t:"kontrol"},{e:"blood test",t:"kan testi"},{e:"recover",t:"iyileşmek"},{e:"cure",t:"tedavi etmek"}]},
{t:"Clothes & Shopping",s:"Kıyafetler ve Alışveriş",e:"put on=giymek, take off=çıkarmak, try on=denemek, suit=yakışmak, fit=uymak. Shopping: trolley, basket, checkout, queue, refund.",st:[],x:[{e:"That colour really suits you.",t:"O renk sana çok yakışıyor."},{e:"Can I get a refund?",t:"Para iadesi alabilir miyim?"}],ti:["suit=yakışmak (stil), fit=uymak (beden)","tight=dar, loose=bol"],w:[{e:"put on",t:"giymek"},{e:"take off",t:"çıkarmak"},{e:"try on",t:"denemek"},{e:"suit",t:"yakışmak"},{e:"fit",t:"uymak"},{e:"match/go with",t:"uyumlu olmak"},{e:"tight",t:"dar"},{e:"loose",t:"bol"},{e:"fashionable",t:"modaya uygun"},{e:"smart",t:"şık"},{e:"casual",t:"günlük"},{e:"boots",t:"bot"},{e:"trainers",t:"spor ayakkabı"},{e:"scarf",t:"atkı"},{e:"sleeve",t:"kol"},{e:"collar",t:"yaka"},{e:"zip",t:"fermuar"},{e:"button",t:"düğme"},{e:"pocket",t:"cep"},{e:"earrings",t:"küpe"},{e:"necklace",t:"kolye"},{e:"bracelet",t:"bileklik"},{e:"ring",t:"yüzük"},{e:"trolley",t:"el arabası"},{e:"basket",t:"sepet"},{e:"checkout",t:"kasa"},{e:"queue",t:"sıra"},{e:"receipt",t:"fiş"},{e:"refund",t:"iade"},{e:"bargain",t:"kelepir"},{e:"special offer",t:"indirim"},{e:"customer",t:"müşteri"}]},
{t:"Food & Cooking",s:"Yemek ve Pişirme",e:"Sebzeler, meyveler, et, pişirme yöntemleri.",st:[],x:[{e:"Could you slice the bread?",t:"Ekmeği dilimler misin?"},{e:"I prefer grilled fish.",t:"Izgara balığı tercih ederim."}],ti:["boil=kaynatmak, fry=kızartmak, bake=fırında pişirmek, grill=ızgara, roast=rosto"],w:[{e:"vegetables",t:"sebzeler"},{e:"carrot",t:"havuç"},{e:"onion",t:"soğan"},{e:"potato",t:"patates"},{e:"tomato",t:"domates"},{e:"pepper",t:"biber"},{e:"lettuce",t:"marul"},{e:"cucumber",t:"salatalık"},{e:"mushroom",t:"mantar"},{e:"garlic",t:"sarımsak"},{e:"fruit",t:"meyve"},{e:"apple",t:"elma"},{e:"orange",t:"portakal"},{e:"banana",t:"muz"},{e:"grape",t:"üzüm"},{e:"strawberry",t:"çilek"},{e:"lemon",t:"limon"},{e:"watermelon",t:"karpuz"},{e:"chicken/beef/lamb/pork",t:"tavuk/sığır/kuzu/domuz"},{e:"fish/seafood",t:"balık/deniz ürünü"},{e:"boil",t:"kaynatmak"},{e:"fry",t:"kızartmak"},{e:"bake",t:"fırında pişirmek"},{e:"grill",t:"ızgarada pişirmek"},{e:"roast",t:"kızartmak (fırında)"},{e:"slice",t:"dilimlemek"},{e:"chop",t:"doğramak"},{e:"peel",t:"soymak"},{e:"stir",t:"karıştırmak"},{e:"recipe",t:"tarif"},{e:"ingredient",t:"malzeme"},{e:"raw",t:"çiğ"},{e:"fresh",t:"taze"},{e:"frozen",t:"dondurulmuş"}]},
{t:"Money",s:"Para ve Finans",e:"earn/make money, save money, spend money, waste money, borrow/lend, owe.",st:[],x:[{e:"I can't afford a new car.",t:"Yeni araba alamam."},{e:"She borrowed £100 from me.",t:"Benden 100 sterlin ödünç aldı."}],ti:["borrow=ödünç almak, lend=ödünç vermek","save=biriktirmek, waste=israf etmek"],w:[{e:"earn/make money",t:"para kazanmak"},{e:"spend money",t:"para harcamak"},{e:"save money",t:"para biriktirmek"},{e:"waste money",t:"para israf etmek"},{e:"borrow",t:"ödünç almak"},{e:"lend",t:"ödünç vermek"},{e:"owe",t:"borçlu olmak"},{e:"afford",t:"parası yetmek"},{e:"cost",t:"mal olmak"},{e:"pay",t:"ödemek"},{e:"charge",t:"ücret almak"},{e:"bill",t:"fatura"},{e:"tax",t:"vergi"},{e:"salary/wage",t:"maaş"},{e:"income",t:"gelir"},{e:"savings",t:"birikim"},{e:"debt",t:"borç"},{e:"cash",t:"nakit"},{e:"coins",t:"bozuk para"},{e:"account",t:"hesap"},{e:"loan",t:"kredi"},{e:"mortgage",t:"ipotek"},{e:"insurance",t:"sigorta"}]},
{t:"City & Transport",s:"Şehir ve Ulaşım",e:"Şehir yaşamı ve ulaşım araçları.",st:[],x:[{e:"The train was delayed by 30 minutes.",t:"Tren 30 dakika gecikti."}],ti:["rush hour=trafik saati, traffic jam=trafik sıkışıklığı"],w:[{e:"bus/train/tram",t:"otobüs/tren/tramvay"},{e:"subway/underground",t:"metro"},{e:"taxi/cab",t:"taksi"},{e:"bicycle/bike",t:"bisiklet"},{e:"motorcycle",t:"motosiklet"},{e:"flight",t:"uçuş"},{e:"passenger",t:"yolcu"},{e:"driver",t:"sürücü"},{e:"ticket",t:"bilet"},{e:"platform",t:"peron"},{e:"station",t:"istasyon"},{e:"airport",t:"havalimanı"},{e:"traffic jam",t:"trafik sıkışıklığı"},{e:"rush hour",t:"trafik saati"},{e:"parking",t:"otopark"},{e:"petrol/gas",t:"benzin"},{e:"speed limit",t:"hız sınırı"},{e:"crossroads",t:"kavşak"},{e:"roundabout",t:"dönel kavşak"},{e:"pedestrian",t:"yaya"},{e:"pavement/sidewalk",t:"kaldırım"},{e:"public transport",t:"toplu taşıma"},{e:"commute",t:"işe gidip gelmek"},{e:"delayed",t:"gecikmeli"},{e:"cancelled",t:"iptal edilmiş"}]}
]},

{c:"İş ve Eğitim",u:[
{t:"Jobs & Career",s:"Meslekler ve Kariyer",e:"apply for=başvurmak, interview=mülakat, promote=terfi, quit/resign=istifa, sack/fire=kovmak.",st:[],x:[{e:"She was promoted after 2 years.",t:"2 yıl sonra terfi etti."},{e:"He was sacked for being late.",t:"Geç kaldığı için kovuldu."}],ti:["experience (deneyim) sayılamaz isim","work (iş) sayılamaz: I had a job ✓ I had a work ✗"],w:[{e:"apply for",t:"başvurmak"},{e:"CV",t:"özgeçmiş"},{e:"interview",t:"mülakat"},{e:"employ",t:"işe almak"},{e:"training",t:"eğitim"},{e:"promote",t:"terfi ettirmek"},{e:"pay rise",t:"zam"},{e:"salary/wage",t:"maaş"},{e:"quit/resign",t:"istifa"},{e:"sack/fire",t:"kovmak"},{e:"unemployed",t:"işsiz"},{e:"retire",t:"emekli olmak"},{e:"part-time/full-time",t:"yarı/tam zamanlı"},{e:"colleague",t:"iş arkadaşı"},{e:"boss/manager",t:"patron/müdür"},{e:"employee/employer",t:"çalışan/işveren"},{e:"deadline",t:"son tarih"},{e:"overtime",t:"fazla mesai"},{e:"be in charge of",t:"sorumlu olmak"},{e:"deal with",t:"ilgilenmek"},{e:"experience",t:"deneyim"},{e:"qualification",t:"yeterlilik"}]},
{t:"Education",s:"Eğitim",e:"Okul, üniversite ve sınav terimleri.",st:[],x:[{e:"I'm studying for my exams.",t:"Sınavlarıma çalışıyorum."},{e:"She graduated from university.",t:"Üniversiteden mezun oldu."}],ti:["pass an exam=geçmek, fail=kalmak","take/sit an exam=sınava girmek"],w:[{e:"primary school",t:"ilkokul"},{e:"secondary school",t:"ortaokul/lise"},{e:"university",t:"üniversite"},{e:"college",t:"yüksekokul"},{e:"student/pupil",t:"öğrenci"},{e:"teacher/lecturer",t:"öğretmen/öğr. üyesi"},{e:"subject",t:"ders/konu"},{e:"lesson/lecture",t:"ders"},{e:"homework/assignment",t:"ödev"},{e:"take an exam",t:"sınava girmek"},{e:"pass",t:"geçmek"},{e:"fail",t:"kalmak"},{e:"grade/mark",t:"not"},{e:"degree",t:"lisans derecesi"},{e:"graduate",t:"mezun olmak"},{e:"scholarship",t:"burs"},{e:"term/semester",t:"dönem"},{e:"research",t:"araştırma"},{e:"knowledge",t:"bilgi"},{e:"skill",t:"beceri"},{e:"certificate",t:"sertifika"}]}
]},

{c:"Eğlence ve Seyahat",u:[
{t:"Sport & Leisure",s:"Spor ve Boş Zaman",e:"play+takım/top: football, tennis. go+-ing: swimming, skiing, jogging. do+bireysel: yoga, karate.",st:[],x:[{e:"They beat us 3-1.",t:"Bizi 3-1 yendiler."},{e:"He scored two goals.",t:"İki gol attı."}],ti:["play→top/takım, go -ing→aktivite, do→bireysel"],w:[{e:"play football/tennis",t:"futbol/tenis oynamak"},{e:"go swimming/skiing",t:"yüzmeye/kayağa gitmek"},{e:"go jogging/hiking",t:"koşuya/yürüyüşe gitmek"},{e:"do yoga/karate",t:"yoga/karate yapmak"},{e:"competition",t:"yarışma"},{e:"match/game",t:"maç"},{e:"win/lose/draw",t:"kazanmak/kaybetmek/berabere"},{e:"beat",t:"yenmek"},{e:"score",t:"gol atmak/puan"},{e:"spectator",t:"seyirci"},{e:"referee",t:"hakem"},{e:"coach",t:"antrenör"},{e:"athlete",t:"sporcu"},{e:"champion",t:"şampiyon"},{e:"medal",t:"madalya"},{e:"tournament",t:"turnuva"},{e:"pitch/court",t:"saha/kort"},{e:"team",t:"takım"},{e:"fan",t:"taraftar"},{e:"record",t:"rekor"},{e:"training",t:"antrenman"}]},
{t:"Travel & Tourism",s:"Seyahat",e:"Uçuş, otel ve tatil terimleri.",st:[],x:[{e:"Can I have a window seat?",t:"Cam kenarı alabilir miyim?"},{e:"I'd like to check out, please.",t:"Çıkış yapmak istiyorum."}],ti:["boarding pass=biniş kartı, gate=kapı","single/double room=tek/çift kişilik oda"],w:[{e:"book/reserve",t:"rezervasyon yapmak"},{e:"cancel",t:"iptal etmek"},{e:"flight",t:"uçuş"},{e:"boarding pass",t:"biniş kartı"},{e:"gate",t:"kapı"},{e:"take off/land",t:"kalkmak/inmek"},{e:"luggage/baggage",t:"bavul"},{e:"passport",t:"pasaport"},{e:"customs",t:"gümrük"},{e:"check in/out",t:"giriş/çıkış"},{e:"single/double room",t:"tek/çift kişilik"},{e:"reception",t:"resepsiyon"},{e:"sightseeing",t:"gezi/tur"},{e:"guided tour",t:"rehberli tur"},{e:"souvenir",t:"hatıra eşyası"},{e:"destination",t:"varış noktası"},{e:"package holiday",t:"paket tatil"},{e:"cruise",t:"kruvaziyer"},{e:"backpacking",t:"sırt çantalı gezi"},{e:"currency",t:"para birimi"},{e:"exchange rate",t:"döviz kuru"}]}
]},

{c:"Teknoloji ve Medya",u:[
{t:"Computers & Internet",s:"Bilgisayar ve İnternet",e:"Temel teknoloji ve internet terimleri.",st:[],x:[{e:"The computer has crashed.",t:"Bilgisayar çöktü."},{e:"Can you download the file?",t:"Dosyayı indirebilir misin?"}],ti:["download≠upload: indirmek≠yüklemek","browser=tarayıcı, search engine=arama motoru"],w:[{e:"keyboard",t:"klavye"},{e:"mouse",t:"fare"},{e:"screen",t:"ekran"},{e:"laptop",t:"dizüstü"},{e:"software/hardware",t:"yazılım/donanım"},{e:"download",t:"indirmek"},{e:"upload",t:"yüklemek"},{e:"click",t:"tıklamak"},{e:"scroll",t:"kaydırmak"},{e:"search engine",t:"arama motoru"},{e:"website",t:"web sitesi"},{e:"browser",t:"tarayıcı"},{e:"attachment",t:"ek dosya"},{e:"password",t:"şifre"},{e:"log in/out",t:"giriş/çıkış"},{e:"crash",t:"çökmek"},{e:"update",t:"güncellemek"},{e:"Wi-Fi",t:"kablosuz internet"},{e:"app",t:"uygulama"},{e:"social media",t:"sosyal medya"},{e:"post",t:"gönderi"},{e:"follower",t:"takipçi"},{e:"content",t:"içerik"},{e:"influencer",t:"fenomen"},{e:"viral",t:"viral"},{e:"trending",t:"gündemde"},{e:"privacy",t:"gizlilik"},{e:"data",t:"veri"},{e:"hack",t:"hacklemek"},{e:"backup",t:"yedekleme"}]},
{t:"News & Media",s:"Haber ve Medya",e:"Gazete, televizyon ve haber terimleri.",st:[],x:[{e:"The article was published yesterday.",t:"Makale dün yayınlandı."}],ti:["headline=başlık, article=makale, journalist=gazeteci"],w:[{e:"headline",t:"başlık (haber)"},{e:"article",t:"makale"},{e:"journalist/reporter",t:"gazeteci/muhabir"},{e:"editor",t:"editör"},{e:"press",t:"basın"},{e:"publish",t:"yayınlamak"},{e:"broadcast",t:"yayınlamak (TV/radyo)"},{e:"channel",t:"kanal"},{e:"documentary",t:"belgesel"},{e:"advertisement/ad",t:"reklam"},{e:"headline",t:"manşet"},{e:"fake news",t:"sahte haber"},{e:"source",t:"kaynak"},{e:"reliable",t:"güvenilir"},{e:"biased",t:"taraflı"},{e:"sensational",t:"sansasyonel"},{e:"survey",t:"anket"},{e:"opinion",t:"görüş"},{e:"debate",t:"tartışma"}]}
]},

{c:"Toplum ve Çevre",u:[
{t:"Environment",s:"Çevre Sorunları",e:"Çevre koruma, kirlilik ve doğa terimleri.",st:[],x:[{e:"We need to reduce pollution.",t:"Kirliliği azaltmalıyız."},{e:"Deforestation is a serious problem.",t:"Ormansızlaşma ciddi bir sorun."}],ti:["pollute→polluted→pollution","recycle=geri dönüştürmek, renewable=yenilenebilir"],w:[{e:"environment",t:"çevre"},{e:"pollution",t:"kirlilik"},{e:"pollute/polluted",t:"kirletmek/kirli"},{e:"recycle",t:"geri dönüştürmek"},{e:"waste",t:"atık/israf"},{e:"climate change",t:"iklim değişikliği"},{e:"global warming",t:"küresel ısınma"},{e:"greenhouse effect",t:"sera etkisi"},{e:"carbon footprint",t:"karbon ayak izi"},{e:"renewable energy",t:"yenilenebilir enerji"},{e:"solar/wind power",t:"güneş/rüzgar enerjisi"},{e:"deforestation",t:"ormansızlaşma"},{e:"endangered species",t:"nesli tehlikedeki türler"},{e:"wildlife",t:"yaban hayatı"},{e:"ecosystem",t:"ekosistem"},{e:"sustainable",t:"sürdürülebilir"},{e:"organic",t:"organik"},{e:"conservation",t:"koruma"},{e:"biodiversity",t:"biyoçeşitlilik"},{e:"emission",t:"emisyon"},{e:"fossil fuel",t:"fosil yakıt"},{e:"drought",t:"kuraklık"},{e:"flood",t:"sel"},{e:"natural disaster",t:"doğal afet"}]},
{t:"Crime & Law",s:"Suç ve Hukuk",e:"Suç türleri ve hukuk terimleri.",st:[],x:[{e:"He was arrested for robbery.",t:"Soygundan tutuklandı."},{e:"The judge sentenced him to 5 years.",t:"Hakim onu 5 yıla mahkum etti."}],ti:["steal→theft→thief, rob→robbery→robber","murder=cinayet, murderer=katil"],w:[{e:"crime",t:"suç"},{e:"criminal",t:"suçlu"},{e:"steal/theft/thief",t:"çalmak/hırsızlık/hırsız"},{e:"rob/robbery/robber",t:"soymak/soygun/soygunci"},{e:"murder/murderer",t:"cinayet/katil"},{e:"burglary/burglar",t:"ev soygunu/hırsız"},{e:"kidnap",t:"adam kaçırmak"},{e:"arrest",t:"tutuklamak"},{e:"evidence",t:"kanıt"},{e:"witness",t:"tanık"},{e:"suspect",t:"şüpheli"},{e:"trial",t:"dava/duruşma"},{e:"judge",t:"hakim"},{e:"jury",t:"jüri"},{e:"lawyer",t:"avukat"},{e:"guilty/innocent",t:"suçlu/masum"},{e:"sentence",t:"ceza vermek"},{e:"prison/jail",t:"hapishane"},{e:"fine",t:"para cezası"},{e:"victim",t:"kurban"},{e:"investigation",t:"soruşturma"},{e:"illegal/legal",t:"yasadışı/yasal"}]}
]},

{c:"Kelime Yapımı",u:[
{t:"Prefixes & Suffixes",s:"Ön Ekler ve Son Ekler",e:"OLUMSUZ: un- (unhappy), im- (impossible), in- (incorrect), dis- (disagree), il- (illegal), ir- (irregular)\nTEKRAR: re- (rewrite, redo)\nFAZLA: over- (overwork), under- (underpay)\n\nİSİM: -ment (government), -tion (education), -ness (happiness), -ity (electricity), -er/-or (teacher, actor)\nSIFAT: -ful (helpful), -less (careless), -able (comfortable), -ous (dangerous), -ive (attractive), -al (national)\nZARF: -ly (quickly)",st:[],x:[{e:"unhappy, impossible, disagree, illegal",t:"mutsuz, imkansız, katılmamak, yasadışı"},{e:"teacher, education, happiness, dangerous",t:"öğretmen, eğitim, mutluluk, tehlikeli"}],ti:["un-/im-/in-/dis-/il-/ir- → olumsuz","-ful → ...li, -less → ...sız","-ment/-tion/-ness → isim, -ly → zarf"],w:[{e:"un-",t:"olumsuz (unhappy)"},{e:"im-/in-/il-/ir-",t:"olumsuz (impossible)"},{e:"dis-",t:"olumsuz (disagree)"},{e:"re-",t:"tekrar (rewrite)"},{e:"over-",t:"fazla (overwork)"},{e:"under-",t:"az (underpay)"},{e:"mis-",t:"yanlış (misunderstand)"},{e:"-ment",t:"isim (government)"},{e:"-tion/-sion",t:"isim (education)"},{e:"-ness",t:"isim (happiness)"},{e:"-ity",t:"isim (electricity)"},{e:"-er/-or",t:"isim (teacher)"},{e:"-ful",t:"sıfat (helpful)"},{e:"-less",t:"sıfat (careless)"},{e:"-able/-ible",t:"sıfat (comfortable)"},{e:"-ous",t:"sıfat (dangerous)"},{e:"-ive",t:"sıfat (attractive)"},{e:"-al",t:"sıfat (national)"},{e:"-ly",t:"zarf (quickly)"}]}
]},
{c:"Ders Fotoğraflarından",u:[
{t:"Coğrafya ve Türkiye",s:"Fotoğraflardan Türkiye ile ilgili kelimeler",e:"Ders fotoğraflarındaki coğrafya ve Türkiye ile ilgili tüm kelimeler.",st:[],x:[{e:"Cappadocia is famous for its picturesque landscape.",t:"Kapadokya pitoresk manzarasıyla ünlüdür."},{e:"The house is perched on a hilltop overlooking the plain.",t:"Ev, ovaya bakan bir tepede konumlanmış."},{e:"Ancient civilizations left remarkable ruins.",t:"Antik uygarlıklar dikkat çekici kalıntılar bıraktı."}],ti:["perched on = üstüne tünemiş","carve out = oymak, yontmak (kayaya)"],w:[{e:"sandstone",t:"kumtaşı"},{e:"diversity",t:"çeşitlilik"},{e:"picturesque",t:"pitoresk, resim gibi"},{e:"sandy",t:"kumlu"},{e:"peninsula",t:"yarımada"},{e:"offer",t:"sunmak"},{e:"cascade down",t:"şelale gibi dökülmek"},{e:"be located in",t:"...da bulunmak"},{e:"lively",t:"canlı, hareketli"},{e:"prosper",t:"gelişmek, zenginleşmek"},{e:"Aegean",t:"Ege"},{e:"including",t:"dahil olmak üzere"},{e:"dynasty",t:"hanedan"},{e:"civilization",t:"medeniyet"},{e:"ruins",t:"kalıntılar"},{e:"boast",t:"övünmek, sahip olmak"},{e:"perched on",t:"üstüne tünemiş"},{e:"stunning",t:"muhteşem"},{e:"mankind",t:"insanlık"},{e:"hilltop",t:"tepe"},{e:"cliff-top",t:"uçurum tepesi"},{e:"overlooking",t:"tepeden bakan"},{e:"attract",t:"cezbetmek"},{e:"remarkable",t:"dikkat çekici"},{e:"plain",t:"ova, düzlük"},{e:"impressive",t:"etkileyici"},{e:"landscape",t:"manzara"},{e:"settlement",t:"yerleşim yeri"},{e:"carve out",t:"oymak, yontmak"},{e:"church",t:"kilise"},{e:"add",t:"eklemek, katmak"}]},

{t:"Doğa ve Macera",s:"Kuzey ışıkları, tur ve doğa gezileri",e:"Doğa gezileri, milli parklar ve macera turizmi kelimeleri.",st:[],x:[{e:"The Northern Lights are a spectacular sight.",t:"Kuzey Işıkları muhteşem bir manzara."},{e:"Hiking through pristine forests is on my bucket list.",t:"Bozulmamış ormanlarda yürüyüş yapmak hayat listemde."}],ti:["a dozen of = bir düzine (12)","bucket list = ölmeden yapılacaklar listesi"],w:[{e:"ultimate",t:"nihai, en üstün"},{e:"situate",t:"konumlandırmak"},{e:"cross-country",t:"kros, doğa yürüyüşü"},{e:"pristine",t:"bozulmamış, el değmemiş"},{e:"man-made",t:"insan yapımı"},{e:"wonderland",t:"harikalar diyarı"},{e:"herd",t:"sürü"},{e:"no easy feat",t:"kolay iş değil"},{e:"wild reindeer",t:"yabani ren geyiği"},{e:"creation",t:"yaratılış, eser"},{e:"forgive",t:"affetmek"},{e:"glory/glorious",t:"şan/şanlı"},{e:"incredible",t:"inanılmaz"},{e:"entire",t:"bütün, tüm"},{e:"footstep",t:"ayak izi"},{e:"flow",t:"akmak, akış"},{e:"at least",t:"en azından"},{e:"royal",t:"kraliyet"},{e:"bucket list",t:"hayat listesi"},{e:"retreat",t:"inziva yeri"},{e:"sight",t:"manzara"},{e:"path",t:"patika, yol"},{e:"ancient",t:"antik"},{e:"moose",t:"Amerikan sığını"},{e:"ascend",t:"tırmanmak, çıkmak"},{e:"descend",t:"inmek, alçalmak"},{e:"stone step",t:"taş basamak"},{e:"slope",t:"yamaç, eğim"},{e:"species",t:"tür"},{e:"a dozen of",t:"bir düzine"},{e:"lush",t:"yemyeşil, bereketli"},{e:"cover",t:"kaplamak"},{e:"valley",t:"vadi"},{e:"continuously",t:"sürekli olarak"},{e:"through",t:"içinden, boyunca"}]},

{t:"Aşırı İklim ve Bağlaçlar",s:"Sıcak, soğuk ve zıtlık bağlaçları",e:"İklim kelimeleri ve despite/although/if only/even if bağlaçları.",st:[],x:[{e:"Despite the harsh winter, locals gathered for the festival.",t:"Sert kışa rağmen yerli halk festivalde toplandı."},{e:"If only I had more time to travel!",t:"Keşke seyahat etmek için daha çok zamanım olsa!"},{e:"Even if it's freezing, we'll go camping.",t:"Buz gibi olsa bile kampa gideceğiz."}],ti:["if only = I wish (keşke)","despite + isim/gerund, although + cümle","only if = if (ancak eğer)"],w:[{e:"extreme",t:"aşırı, uç"},{e:"be known as",t:"...olarak bilinmek"},{e:"degrees",t:"derece"},{e:"Celsius/Centigrade",t:"Santigrat"},{e:"republic",t:"cumhuriyet"},{e:"minus",t:"eksi"},{e:"locals",t:"yerel halk"},{e:"region",t:"bölge"},{e:"gather",t:"toplanmak"},{e:"especially = particularly",t:"özellikle"},{e:"take part in",t:"katılmak"},{e:"inhabited",t:"yerleşik"},{e:"experience",t:"deneyim"},{e:"sand dune",t:"kum tepesi"},{e:"because of",t:"nedeniyle"},{e:"harsh",t:"sert, zorlu"},{e:"freeze",t:"donmak"},{e:"temperature",t:"sıcaklık"},{e:"instantly",t:"anında"},{e:"drop",t:"düşmek"},{e:"thick vs thin",t:"kalın ve ince"},{e:"below",t:"altında"},{e:"fur",t:"kürk"},{e:"heat/heated",t:"ısı/ısıtılmış"},{e:"land",t:"kara, arazi"},{e:"beauty",t:"güzellik"},{e:"what if",t:"ya ...olursa?"},{e:"if only = I wish",t:"keşke"},{e:"even if",t:"...olsa bile"},{e:"despite + noun/gerund",t:"...e rağmen"},{e:"although + clause",t:"...olmasına rağmen"},{e:"only if = if",t:"ancak eğer"}]},

{t:"Sosyal Medya ve Etki",s:"Sosyal medyanın hayatımıza etkisi",e:"Sosyal medya, uygulamalar ve bunların etkileri.",st:[],x:[{e:"Social media has a huge impact on mental health.",t:"Sosyal medyanın ruh sağlığına büyük etkisi var."},{e:"She's an influencer with millions of followers.",t:"Milyonlarca takipçisi olan bir fenomen."},{e:"Fake news can spread quickly on social media.",t:"Sahte haberler sosyal medyada hızla yayılabilir."}],ti:["influencer = sosyal medya fenomeni","lead to = ...e yol açmak"],w:[{e:"comfort",t:"rahatlık"},{e:"survey",t:"anket"},{e:"rise",t:"yükseliş"},{e:"launch",t:"başlatmak, piyasaya sürmek"},{e:"global sensation",t:"küresel sansasyon"},{e:"lip-syncing",t:"dudak senkronu"},{e:"content",t:"içerik"},{e:"influencer",t:"fenomen"},{e:"isolated",t:"izole, yalıtılmış"},{e:"have an impact on",t:"...üzerinde etkisi olmak"},{e:"addictive",t:"bağımlılık yapan"},{e:"privacy",t:"gizlilik"},{e:"ban",t:"yasaklamak"},{e:"due to",t:"nedeniyle"},{e:"concern",t:"endişe"},{e:"despite",t:"...e rağmen"},{e:"issue",t:"sorun, mesele"},{e:"advertise",t:"reklam yapmak"},{e:"promote",t:"tanıtmak"},{e:"item",t:"öğe, ürün"},{e:"as a result",t:"sonuç olarak"},{e:"impact",t:"etki"},{e:"mental",t:"zihinsel"},{e:"connect with",t:"bağlantı kurmak"},{e:"effect (n)",t:"etki (isim)"},{e:"affect (v)",t:"etkilemek (fiil)"},{e:"lead to",t:"...e yol açmak"},{e:"anxiety",t:"kaygı"},{e:"low self-esteem",t:"düşük özgüven"},{e:"unrealistic expectations",t:"gerçekçi olmayan beklentiler"},{e:"trend",t:"eğilim, trend"},{e:"stay updated",t:"güncel kalmak"},{e:"stay connected",t:"bağlantıda kalmak"},{e:"keep in touch",t:"iletişimde kalmak"},{e:"meet in person",t:"yüz yüze görüşmek"},{e:"interaction",t:"etkileşim"},{e:"consequence",t:"sonuç"},{e:"distraction",t:"dikkat dağıtıcı"},{e:"focus on",t:"odaklanmak"},{e:"efficient/ly",t:"verimli/verimli olarak"},{e:"spread",t:"yaymak, yayılmak"},{e:"application",t:"uygulama"},{e:"user",t:"kullanıcı"},{e:"business-oriented",t:"iş odaklı"},{e:"target",t:"hedef"},{e:"upload ≠ download",t:"yüklemek ≠ indirmek"},{e:"pin",t:"sabitlemek"},{e:"collection",t:"koleksiyon"},{e:"theme",t:"tema"},{e:"such as",t:"gibi, örneğin"},{e:"respective",t:"ilgili, kendi"}]},

{t:"Medya ve Haber",s:"Gazete, haber ve sahte haberler",e:"Haber, medya ve bilgi kaynakları.",st:[],x:[{e:"Sensational headlines compete for attention.",t:"Sansasyonel başlıklar dikkat için yarışır."},{e:"Is this article from an authentic source?",t:"Bu makale gerçek bir kaynaktan mı?"}],ti:["scroll through = kaydırarak bakmak","fake news = sahte haber"],w:[{e:"receive",t:"almak"},{e:"instead of",t:"...yerine"},{e:"recent",t:"son, yakın zamanlı"},{e:"survey",t:"anket"},{e:"via",t:"aracılığıyla"},{e:"decrease",t:"azalmak"},{e:"article",t:"makale"},{e:"scroll through",t:"kaydırarak bakmak"},{e:"content",t:"içerik"},{e:"headline",t:"başlık (haber)"},{e:"average",t:"ortalama"},{e:"multiple",t:"çoklu"},{e:"therefore",t:"bu nedenle"},{e:"compete for attention",t:"dikkat için yarışmak"},{e:"sensational",t:"sansasyonel"},{e:"ridiculous",t:"saçma, gülünç"},{e:"due to",t:"nedeniyle"},{e:"authentic",t:"özgün, gerçek"},{e:"in fact",t:"aslında"},{e:"likely",t:"muhtemel"},{e:"spread",t:"yaymak"},{e:"truth",t:"gerçek"},{e:"be worth",t:"değmek"},{e:"be up to",t:"...a kalmak"}]},

{t:"Biyografi ve Spor",s:"Ünlü sporcular ve başarı hikayeleri",e:"Sporcular, yarışmalar ve kariyer başarıları.",st:[],x:[{e:"He achieved success at the age of 20.",t:"20 yaşında başarıya ulaştı."},{e:"She was crowned champion in three consecutive years.",t:"Üç yıl arka arkaya şampiyon oldu."},{e:"His unique personality is based on self-belief.",t:"Benzersiz kişiliği özgüvene dayanır."}],ti:["Kelime türetme: sprint→sprinter, run→runner","talent = skill, talented = skillful","emotional → emotionally"],w:[{e:"migration/immigration",t:"göç"},{e:"migrant/immigrant",t:"göçmen"},{e:"wrestle/wrestling",t:"güreşmek/güreş"},{e:"raise (in)",t:"büyütmek"},{e:"grow (in)",t:"büyümek"},{e:"trainer",t:"antrenör"},{e:"notice",t:"fark etmek"},{e:"at the age of",t:"...yaşında"},{e:"remarkable",t:"dikkat çekici"},{e:"feature",t:"özellik"},{e:"short stature",t:"kısa boy"},{e:"exceptional = special",t:"olağanüstü"},{e:"decide",t:"karar vermek"},{e:"suitable = a better fit",t:"uygun"},{e:"weightlifter",t:"halterci"},{e:"weigh",t:"tartmak, ...kilo gelmek"},{e:"dis/approve",t:"onaylamamak/onaylamak"},{e:"passion/passionate",t:"tutku/tutkulu"},{e:"triple",t:"üçlü"},{e:"consecutive",t:"art arda"},{e:"competition",t:"yarışma"},{e:"unique",t:"benzersiz"},{e:"personality",t:"kişilik"},{e:"self-belief",t:"özgüven"},{e:"religious",t:"dini"},{e:"political",t:"siyasi"},{e:"conviction",t:"inanç"},{e:"illustrate",t:"göstermek"},{e:"crowned",t:"taçlandırılmış"},{e:"as well as",t:"...yanı sıra"},{e:"bury",t:"gömmek"},{e:"sprinter/runner",t:"sürat koşucusu/koşucu"},{e:"jogger/hiker/walker",t:"koşucu/yürüyüşçü/yürüyen"},{e:"race/racer",t:"yarış/yarışmacı"},{e:"though",t:"olsa da, ama"},{e:"well-off",t:"varlıklı"},{e:"support",t:"desteklemek"},{e:"emotional/emotionally",t:"duygusal/duygusal olarak"},{e:"talent = skill",t:"yetenek"},{e:"talented = skillful",t:"yetenekli"},{e:"participate in = take part in = join",t:"katılmak"},{e:"occasion",t:"durum, vesile"},{e:"injury",t:"yaralanma"},{e:"paralysis",t:"felç"},{e:"memory loss",t:"hafıza kaybı"},{e:"result in",t:"...ile sonuçlanmak"},{e:"suffer from",t:"...den muzdarip olmak"},{e:"4x100-metre relay",t:"4x100 metre bayrak"}]},

{t:"Kelime Türetme ve Etkinlikler",s:"Suffixes, prefixes ve karma kelimeler",e:"Ön ve son ekler ile kelime türetme, mahalle hayatı ve etkinlikler.",st:[],x:[{e:"I generally get on well with helpful people.",t:"Genellikle yardımsever insanlarla iyi geçinirim."},{e:"Nowadays, people give a lot of importance to their personal development.",t:"Günümüzde insanlar kişisel gelişime çok önem veriyor."},{e:"Scientists have been searching for cures of infectious diseases.",t:"Bilim insanları bulaşıcı hastalıklara çare arıyor."}],ti:["-ful → helpful, -ment → investment","in-law → evlilik akrabalığı","found→founded (kurmak) vs find→found (bulmak)"],w:[{e:"planet",t:"gezegen"},{e:"plate",t:"tabaka"},{e:"plant",t:"bitki"},{e:"environment",t:"çevre"},{e:"achieve success",t:"başarıya ulaşmak"},{e:"fight against",t:"...ile mücadele etmek"},{e:"pollute → polluted → pollution",t:"kirletmek/kirli/kirlilik"},{e:"harm",t:"zarar vermek"},{e:"marine",t:"denizle ilgili"},{e:"toxic",t:"zehirli"},{e:"found - founded (kurmak)",t:"kurmak - kurdu"},{e:"find - found (bulmak)",t:"bulmak - buldu"},{e:"founder",t:"kurucu"},{e:"foundation",t:"vakıf, temel"},{e:"deforestation",t:"ormansızlaşma"},{e:"overfishing",t:"aşırı avlanma"},{e:"il-legal(-ly)",t:"yasadışı"},{e:"legalize",t:"yasallaştırmak"},{e:"whale → whaling",t:"balina → balina avcılığı"},{e:"raise awareness",t:"farkındalık yaratmak"},{e:"be known for",t:"...ile tanınmak"},{e:"peaceful",t:"barışçıl"},{e:"govern → government",t:"yönetmek → hükümet"},{e:"law → lawyer",t:"hukuk → avukat"},{e:"in-law (evlilik)",t:"kayın-"},{e:"groom / bride",t:"damat / gelin"},{e:"son-in-law",t:"damat (kızın eşi)"},{e:"daughter-in-law",t:"gelin (oğlun eşi)"},{e:"square",t:"meydan"},{e:"pigeon",t:"güvercin"},{e:"feed",t:"beslemek"},{e:"pub",t:"birahane"},{e:"row",t:"sıra"},{e:"have sb over for",t:"birini davet etmek"},{e:"immigrate",t:"göç etmek"},{e:"piece",t:"parça"},{e:"suburb",t:"banliyö"},{e:"be (not) like",t:"benzer (benzemez)"},{e:"look like",t:"...gibi görünmek"},{e:"several",t:"birkaç"},{e:"field",t:"tarla, alan"},{e:"be proud of",t:"gurur duymak"},{e:"mow the lawn",t:"çim biçmek"},{e:"pond",t:"gölet"},{e:"hedge",t:"çit"},{e:"traditional",t:"geleneksel"},{e:"gain independence",t:"bağımsızlık kazanmak"},{e:"make/earn money",t:"para kazanmak"},{e:"win a game/competition",t:"oyun/yarışma kazanmak"},{e:"optimistic ≠ pessimistic",t:"iyimser ≠ kötümser"},{e:"helpful",t:"yardımsever"},{e:"investment",t:"yatırım"},{e:"creator",t:"yaratıcı"},{e:"importance",t:"önem"},{e:"infectious",t:"bulaşıcı"},{e:"greatly",t:"büyük ölçüde"}]},

{t:"Afet ve Güvenlik",s:"Doğal afetler ve kurtarma",e:"Afet, kurtarma ve güvenlik terimleri.",st:[],x:[{e:"Despite the challenge, the residents were safe.",t:"Zorluğa rağmen sakinler güvendeydi."},{e:"Highly trained rescuers helped tow the vehicle away.",t:"İyi eğitimli kurtarıcılar aracı çekmeye yardım etti."}],ti:["reside (v) → resident (n) → residence (n) → residential (adj)","break apart = parçalanmak, roll over = devrilmek"],w:[{e:"common",t:"yaygın"},{e:"reside (v)",t:"ikamet etmek"},{e:"resident (n)",t:"sakin"},{e:"residence (n)",t:"ikamet yeri"},{e:"residential (adj)",t:"konut ile ilgili"},{e:"prevent",t:"önlemek"},{e:"chunk",t:"büyük parça"},{e:"safety",t:"güvenlik"},{e:"especially",t:"özellikle"},{e:"disaster",t:"afet"},{e:"track",t:"izlemek, iz"},{e:"rope",t:"halat, ip"},{e:"cannon",t:"top (silah)"},{e:"push",t:"itmek"},{e:"attach",t:"bağlamak"},{e:"tow sth away",t:"çekip götürmek"},{e:"rough",t:"sert, engebeli"},{e:"break apart",t:"parçalanmak"},{e:"roll over",t:"devrilmek"},{e:"highly trained",t:"iyi eğitimli"},{e:"condition",t:"durum, koşul"},{e:"challenge",t:"zorluk"},{e:"blizzard",t:"kar fırtınası"},{e:"floods",t:"sel baskınları"},{e:"tornado",t:"hortum"},{e:"storm",t:"fırtına"},{e:"drought = lack of rain",t:"kuraklık"},{e:"underwatering",t:"az sulama"},{e:"overwatering",t:"aşırı sulama"}]}
]}
];
const R=[
{t:"Insomnia (Uykusuzluk)",l:"B1",p:"When the task at hand is to get a good night's sleep, trying hard is not the way to succeed. Twisting and turning in search of a comfortable position makes your body do the opposite of what it is supposed to do. Instead of slowing down, your heartbeat races. Instead of relaxing, your muscles twitch.\n\nTen million people in the United States alone are seeking medical help for chronic insomnia. Specialists agree that psychological problems are a cause, but bad habits can have the same effect. These include too little daytime activity and, ironically, too much exercise.\n\nSleeping late on weekends can disrupt your body's clock. Even though exercise tires you out, if it is too strenuous just before bedtime, it can cause a restless night.\n\nWhat should you do? Forget sleeping pills — they can actually cause insomnia after three days. Experts recommend drinking milk or eating cheese, because they contain natural sleep-producing aids.",w:[{e:"insomnia",t:"uykusuzluk"},{e:"heartbeat",t:"kalp atışı"},{e:"muscles",t:"kaslar"},{e:"chronic",t:"kronik"},{e:"symptom",t:"belirti"},{e:"disrupt",t:"bozmak"},{e:"strenuous",t:"yorucu"},{e:"restless",t:"huzursuz"},{e:"remedy",t:"çare"},{e:"aid",t:"yardımcı"}],q:[{q:"Uykusuzluk için uzmanlar ne önerir?",o:["Uyku hapı","Yoğun egzersiz","Süt veya peynir","Geç uyumak"],c:2},{q:"'strenuous' ne demek?",o:["Rahat","Yorucu","Hızlı","Kolay"],c:1},{q:"Hafta sonu geç uyumak ne yapar?",o:["İyileştirir","Vücut saatini bozar","Kas gevşetir","Stresi azaltır"],c:1}]},

{t:"Acupuncture (Akupunktur)",l:"B1-B2",p:"Acupuncture is based on the Chinese model of health. In this model, there are three main systems: circulatory, nervous, and energy movement.\n\nThe Chinese believe all life is controlled by two basic energy movements: outward and inward. Health depends on the balance between them. If this balance is disturbed, diseases occur.\n\nThis energy moves along 26 channels called meridians. Each connects to a different body part. When a meridian is blocked, diseases occur. Doctors place needles at specific points to unblock energy.\n\nToday, acupuncture is used in operations instead of anaesthetics. In the East, nearly three million doctors regularly use it.",w:[{e:"acupuncture",t:"akupunktur"},{e:"needle",t:"iğne"},{e:"circulatory",t:"dolaşım"},{e:"balance",t:"denge"},{e:"disturbed",t:"bozulmuş"},{e:"disease",t:"hastalık"},{e:"meridian",t:"enerji kanalı"},{e:"blocked",t:"tıkanmış"},{e:"cure",t:"tedavi etmek"},{e:"anaesthetic",t:"anestezi"}],q:[{q:"Akupunktur neye dayanır?",o:["Batı tıbbı","Çin modeli","Hint yoga","Modern cerrahi"],c:1},{q:"Meridyen nedir?",o:["İğne türü","Enerji kanalı","Kas","Sinir"],c:1},{q:"Hastalıklar ne zaman oluşur?",o:["Denge bozulunca","Çok uyuyunca","Az yiyince","Spor yapınca"],c:0}]},

{t:"Maisie's Amazing Animals",l:"A2-B1",p:"An ambulance and the RSPCA were called to Maisie MacDonald's home in Glasgow. A doctor discovered the most bizarre collection of animals sharing the house with 83-year-old Maisie.\n\nJohn McInnes from Edinburgh Zoo said: 'I have never seen so many animals in anyone's home. Maisie has done a wonderful job — none has been neglected.'\n\nWhat did they find? Cages of birds going up three flights of stairs. A goat and rabbits on the first floor. Ducks in the bathroom. Fish tanks with terrapins and baby alligators. And on the top floor — a fully grown tiger living in the attic! But it was as tame as a kitten.\n\nFrom her hospital bed, Maisie said: 'My animals are my whole life. I often send my dog to the post office with a note to get things for me.'",w:[{e:"bizarre",t:"tuhaf"},{e:"neglected",t:"ihmal edilmiş"},{e:"cage",t:"kafes"},{e:"flight of stairs",t:"kat merdiveni"},{e:"goat",t:"keçi"},{e:"rabbit",t:"tavşan"},{e:"alligator",t:"timsah"},{e:"attic",t:"çatı katı"},{e:"tame",t:"evcil"},{e:"kitten",t:"yavru kedi"}],q:[{q:"En şaşırtıcı hayvan hangisi?",o:["Timsah","Keçi","Kaplan","Ördek"],c:2},{q:"tame ne demek?",o:["Vahşi","Evcil","Büyük","Hızlı"],c:1},{q:"Maisie kaç yaşında?",o:["73","83","93","63"],c:1}]},

{t:"Margaret Mee - The Amazon Explorer",l:"B1-B2",p:"Artist, adventurer, explorer, botanist and rain forest conservationist are some ways of describing Margaret Mee, a remarkable woman who spent the last 36 years painting the Amazon flora.\n\nIn 1956, at the age of 47, the already accomplished artist made her first Amazon expedition to observe, collect and paint the flowers of the region. Thus began a series of 15 expeditions, the last of which was in May of 1988, successfully to fulfill her dream to paint the flowers of the rare moonflower cactus.\n\nDuring her journeys, she witnessed the destruction of the rainforest and became one of the earliest voices calling for its preservation. Her paintings are not only beautiful works of art but also scientific documents of species that may no longer exist.",w:[{e:"adventurer",t:"maceracı"},{e:"explorer",t:"kaşif"},{e:"botanist",t:"botanikçi"},{e:"conservationist",t:"doğa korumacı"},{e:"remarkable",t:"dikkat çekici"},{e:"flora",t:"bitki örtüsü"},{e:"accomplished",t:"başarılı, usta"},{e:"expedition",t:"keşif gezisi"},{e:"fulfill",t:"gerçekleştirmek"},{e:"rare",t:"nadir"},{e:"witness",t:"tanık olmak"},{e:"destruction",t:"yıkım"},{e:"preservation",t:"koruma"}],q:[{q:"Margaret Mee kaç Amazon keşif gezisi yaptı?",o:["10","15","20","36"],c:1},{q:"'accomplished' ne demek?",o:["Genç","Başarılı, usta","Yorgun","Yaşlı"],c:1},{q:"Neye çağrıda bulundu?",o:["Yağmur ormanlarının korunmasına","Şehirleşmeye","Turizme","Endüstriye"],c:0}]},

{t:"Laying Insomnia to Rest",l:"B2",p:"According to Joyce and Kales, two psychiatrists, insomniacs present a consistent personality profile. They take things hard, feel they haven't lived 'the right kind of life', and are nervous and tense.\n\nThomas Coates of the University of California says another characteristic common to insomniacs is that they spend an excessive amount of time thinking about sleep. Contrary to the image of bad sleepers as workaholics, Coates's study indicates that insomniacs spend more time relaxing than others do. Their relative inactivity during the day may alter the body's clock.\n\nRobert Watson tells patients to rise at the same time each day, even after a night of poor sleep. After a while, sleep improves. Even though exercise tires you out, it won't guarantee a sound sleep. If it is too strenuous, especially just before bedtime, it can drive your pulse too high, causing a restless night.",w:[{e:"psychiatrist",t:"psikiyatrist"},{e:"insomniac",t:"uykusuzluk çeken"},{e:"consistent",t:"tutarlı"},{e:"nervous and tense",t:"gergin ve stresli"},{e:"characteristic",t:"özellik"},{e:"excessive",t:"aşırı"},{e:"contrary to",t:"...aksine"},{e:"workaholic",t:"iş bağımlısı"},{e:"inactivity",t:"hareketsizlik"},{e:"alter",t:"değiştirmek"},{e:"guarantee",t:"garanti etmek"},{e:"sound sleep",t:"sağlam uyku"},{e:"pulse",t:"nabız"}],q:[{q:"Uykusuzluk çekenlerin ortak özelliği nedir?",o:["Çok çalışkanlar","Uyku hakkında çok düşünürler","Az yerler","Erken uyurlar"],c:1},{q:"Robert Watson ne öneriyor?",o:["Uyku hapı almayı","Her gün aynı saatte kalkmayı","Geç yatmayı","Kafein tüketmeyi"],c:1},{q:"'strenuous' ne demek?",o:["Kolay","Yorucu","Yavaş","Rahat"],c:1}]}
];

/* ══════ QUIZ GENERATOR ══════ */
function mkQ(ws){var qs=[];if(!ws||ws.length<4)return qs;var sh=ws.slice().sort(function(){return Math.random()-0.5});for(var i=0;i<Math.min(sh.length,12)&&qs.length<8;i++){var c=sh[i];var ot=ws.filter(function(x){return x.e!==c.e}).sort(function(){return Math.random()-0.5}).slice(0,3);if(ot.length<3)continue;var ops=[c.t,ot[0].t,ot[1].t,ot[2].t];var ci=Math.floor(Math.random()*4);var tmp=ops[0];ops[0]=ops[ci];ops[ci]=tmp;qs.push({q:'"'+c.e+'" ne demek?',o:ops,c:ci,x:c.e+" = "+c.t})}return qs}

/* ══════ APP ══════ */
export default function App(){
var[tab,sTab]=useState("grammar");var[vw,sVw]=useState("home");var[unit,sUnit]=useState(null);var[oc,sOc]=useState(null);var[qi,sQi]=useState(0);var[sl,sSl]=useState(null);var[an,sAn]=useState(false);var[sc,sSc]=useState(0);var[dn,sDn]=useState(false);var[qqs,sQqs]=useState([]);var[rd,sRd]=useState(null);
var cats=tab==="grammar"?G:V;var tot=0;cats.forEach(function(c){tot+=c.u.length});
function goH(){sVw("home");sUnit(null);sRd(null)}
function oU(u){sUnit(u);sVw("lesson")}
function oR(r){sRd(r);sVw("reading")}
function sQ(ws,isR){var q=isR?ws:mkQ(ws);sQqs(q);sVw("quiz");sQi(0);sSl(null);sAn(false);sSc(0);sDn(false)}
function pk(i){if(an)return;sSl(i);sAn(true);if(i===qqs[qi].c)sSc(function(s){return s+1})}
function nx(){if(qi+1>=qqs.length)sDn(true);else{sQi(function(q){return q+1});sSl(null);sAn(false)}}
var fw=["Hello","Grammar","Verb","Learn","Noun","Quiz","Read","English","Book","Study"];
return(<div style={{fontFamily:"Inter,system-ui,sans-serif",background:"#f7f7f8",minHeight:"100vh",color:"#121217"}}>
<style>{"@keyframes spin{to{transform:rotate(360deg)}}@keyframes fadeUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes fW{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}@keyframes fS{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}"}</style>

{vw==="home"&&<div>
<div style={{background:"#ffc233",padding:"10px 20px",textAlign:"center"}}><span style={{fontSize:13,fontWeight:600,color:"#121217",letterSpacing:"0.5px",textTransform:"uppercase"}}>English Learning Platform — Gramer, Kelime, Okuma ve Quiz</span></div>

<div style={{background:"#5423e7",padding:"48px 20px 44px",position:"relative",overflow:"hidden"}}>
<div style={{position:"absolute",top:-60,right:-40,width:200,height:200,borderRadius:"50%",background:"rgba(112,71,235,0.4)"}}/>
<div style={{position:"absolute",bottom:-40,left:-20,width:140,height:140,borderRadius:"50%",background:"rgba(255,194,51,0.1)"}}/>
{fw.map(function(w,i){return <span key={i} style={{position:"absolute",color:"rgba(255,255,255,0.06)",fontSize:14+(i%3)*6,fontWeight:700,left:(8+(i*9)%80)+"%",top:(10+(i*13)%75)+"%",transform:"rotate("+(-12+i*5)+"deg)",animation:"fW "+(5+i*0.7)+"s ease-in-out infinite",animationDelay:i*0.3+"s"}}>{w}</span>})}
<svg style={{position:"absolute",top:16,right:"10%",animation:"fS 5s ease-in-out infinite",opacity:0.5}} width="50" height="50" viewBox="0 0 50 50" fill="none"><rect x="5" y="3" width="28" height="38" rx="3" fill="#7047eb" opacity="0.3"/><rect x="12" y="7" width="28" height="38" rx="3" fill="#ffc233" opacity="0.25"/><path d="M16 18h16M16 24h12M16 30h14" stroke="#fff" strokeWidth="1.5" opacity="0.5"/></svg>
<div style={{maxWidth:600,margin:"0 auto",position:"relative",animation:"fadeUp 0.8s ease"}}>
<div style={{color:"#ffc233",fontSize:13,fontWeight:600,textTransform:"uppercase",letterSpacing:"2.5px",marginBottom:14}}>Kapsamlı İngilizce Eğitimi</div>
<h1 style={{fontSize:42,fontWeight:800,color:"#fff",letterSpacing:"-1.6px",lineHeight:1.05,marginBottom:14}}>İngilizce Öğren.</h1>
<p style={{color:"rgba(255,255,255,0.8)",fontSize:15,lineHeight:1.65,marginBottom:24,maxWidth:400}}>Gramer kuralları, 500+ kelime, okuma parçaları ve interaktif quizler ile İngilizceni geliştir.</p>
<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>
{["📖 Gramer","📚 Kelime","📄 Okuma","📝 Quiz"].map(function(t){return <div key={t} style={{background:"rgba(255,255,255,0.12)",borderRadius:40,padding:"7px 16px",color:"#fff",fontSize:12,fontWeight:500}}>{t}</div>})}
</div></div></div>

<div style={{background:"#fff",borderBottom:"1px solid #d1d1db",position:"sticky",top:0,zIndex:10}}>
<div style={{maxWidth:600,margin:"0 auto",display:"flex",padding:"0 16px"}}>
{[["grammar","Gramer"],["vocab","Kelime"],["reading","Okuma"]].map(function(x){return <button key={x[0]} onClick={function(){sTab(x[0]);sOc(null)}} style={{flex:1,padding:"14px 0",border:"none",cursor:"pointer",fontSize:14,fontWeight:tab===x[0]?600:400,background:"transparent",color:tab===x[0]?"#5423e7":"#6c6c89",borderBottom:tab===x[0]?"2px solid #5423e7":"2px solid transparent"}}>{x[1]}</button>})}
</div></div>

<div style={{maxWidth:600,margin:"0 auto",padding:"20px 16px 60px"}}>
{tab==="reading"?<div>
<p style={{color:"#6c6c89",fontSize:14,marginBottom:16}}>{R.length} okuma parçası</p>
{R.map(function(r,i){return <div key={i} onClick={function(){oR(r)}} style={{background:"#fff",borderRadius:24,padding:"20px 24px",marginBottom:10,border:"1px solid #d1d1db",cursor:"pointer"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
<div><div style={{fontSize:15,fontWeight:600}}>{r.t}</div><div style={{fontSize:12,color:"#6c6c89",marginTop:2}}>{r.w.length} kelime</div></div>
<span style={{background:"#e5b5fe",color:"#5423e7",fontSize:11,fontWeight:600,padding:"3px 12px",borderRadius:40}}>{r.l}</span>
</div></div>})}
</div>:<div>
<p style={{color:"#6c6c89",fontSize:14,marginBottom:16}}>{cats.length} kategori, {tot} konu</p>
{cats.map(function(cat,ci){return <div key={ci} style={{marginBottom:8,animation:"fadeUp 0.4s ease",animationDelay:ci*0.04+"s",animationFillMode:"both"}}>
<button onClick={function(){sOc(oc===ci?null:ci)}} style={{width:"100%",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px 22px",background:"#fff",border:"1px solid #d1d1db",borderRadius:oc===ci?"20px 20px 0 0":20,cursor:"pointer",transition:"all 0.2s"}}>
<div style={{display:"flex",alignItems:"center",gap:10}}>
<span style={{fontSize:15,fontWeight:600}}>{cat.c}</span>
<span style={{background:"#e5b5fe",color:"#5423e7",fontSize:11,fontWeight:600,padding:"2px 10px",borderRadius:40}}>{cat.u.length}</span>
</div>
<span style={{color:"#6c6c89",transform:oc===ci?"rotate(180deg)":"",transition:"0.3s",display:"inline-block"}}>▾</span>
</button>
{oc===ci&&<div style={{background:"#fff",border:"1px solid #d1d1db",borderTop:"none",borderRadius:"0 0 20px 20px"}}>
{cat.u.map(function(u,ui){return <div key={ui} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 22px",borderBottom:ui<cat.u.length-1?"1px solid #f7f7f8":"none",gap:10}}>
<div style={{flex:1}}><div style={{fontSize:14,fontWeight:500}}>{u.t}</div><div style={{fontSize:12,color:"#6c6c89"}}>{u.s}</div></div>
<div style={{display:"flex",gap:6,flexShrink:0}}>
<button onClick={function(){oU(u)}} style={{padding:"7px 14px",borderRadius:8,border:"none",background:"#121217",color:"#fff",fontSize:12,fontWeight:500,cursor:"pointer"}}>Öğren →</button>
<button onClick={function(){sQ(u.w,false)}} style={{padding:"7px 14px",borderRadius:8,border:"1px solid #d1d1db",background:"#fff",color:"#121217",fontSize:12,fontWeight:500,cursor:"pointer"}}>Quiz</button>
</div></div>})}
</div>}
</div>})}
</div>}
</div></div>}

{vw==="lesson"&&unit&&<div style={{maxWidth:600,margin:"0 auto",padding:"24px 16px 40px",animation:"fadeUp 0.5s ease"}}>
<button onClick={goH} style={{background:"#fff",border:"1px solid #d1d1db",color:"#6c6c89",fontSize:13,cursor:"pointer",padding:"8px 16px",borderRadius:8,marginBottom:24}}>← Geri</button>
<h2 style={{fontSize:28,fontWeight:800,letterSpacing:"-1px",marginBottom:6}}>{unit.t}</h2>
<p style={{color:"#6c6c89",fontSize:15,marginBottom:28}}>{unit.s}</p>
{unit.e&&<div style={{background:"#5423e7",borderRadius:32,padding:"28px 32px",marginBottom:24,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-20,right:-20,width:80,height:80,borderRadius:"50%",background:"rgba(112,71,235,0.5)"}}/><div style={{position:"relative"}}><div style={{color:"#ffc233",fontSize:12,fontWeight:600,textTransform:"uppercase",letterSpacing:"2px",marginBottom:10}}>Açıklama</div><div style={{color:"#fff",fontSize:14,lineHeight:1.8,whiteSpace:"pre-wrap"}}>{unit.e}</div></div></div>}
{unit.st&&unit.st.length>0&&<div style={{marginBottom:24}}><div style={{color:"#6c6c89",fontSize:12,fontWeight:600,textTransform:"uppercase",letterSpacing:"2px",marginBottom:12}}>Yapılar</div>{unit.st.map(function(s,i){return <div key={i} style={{background:"#fff",borderRadius:32,padding:"22px 28px",border:"1px solid #d1d1db",marginBottom:10}}><div style={{fontSize:15,fontWeight:600,color:"#5423e7",marginBottom:8}}>{s.l}</div><div style={{fontSize:13,fontFamily:"monospace",background:"#f7f7f8",borderRadius:8,padding:"8px 14px"}}>{s.f}</div>{s.x&&<div style={{marginTop:10,paddingLeft:14,borderLeft:"3px solid #ffc233"}}><div style={{fontSize:13}}>{s.x}</div>{s.r&&<div style={{color:"#6c6c89",fontSize:12,marginTop:2}}>→ {s.r}</div>}</div>}</div>})}</div>}
{unit.w&&unit.w.length>0&&<div style={{background:"#fff",borderRadius:32,padding:"24px 28px",marginBottom:24,border:"1px solid #d1d1db"}}><div style={{color:"#6c6c89",fontSize:12,fontWeight:600,textTransform:"uppercase",letterSpacing:"2px",marginBottom:12}}>Kelimeler ({unit.w.length})</div>{unit.w.map(function(w,i){return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:i<unit.w.length-1?"1px solid #f7f7f8":"none"}}><span style={{fontSize:14,fontWeight:600}}>{w.e}</span><span style={{fontSize:12,color:"#5423e7",fontWeight:500,background:"#e5b5fe33",padding:"2px 10px",borderRadius:16}}>{w.t}</span></div>})}</div>}
{unit.x&&unit.x.length>0&&<div style={{marginBottom:24}}><div style={{color:"#6c6c89",fontSize:12,fontWeight:600,textTransform:"uppercase",letterSpacing:"2px",marginBottom:12}}>Örnekler</div>{unit.x.map(function(e,i){return <div key={i} style={{background:"#fff",borderRadius:14,padding:"14px 20px",marginBottom:6,border:"1px solid #d1d1db"}}><div style={{fontSize:13,lineHeight:1.5}}>{e.e||e.en}</div><div style={{color:"#6c6c89",fontSize:12,marginTop:3}}>→ {e.t||e.tr}</div></div>})}</div>}
{unit.ti&&unit.ti.length>0&&<div style={{background:"#f7f7f8",borderRadius:32,padding:"22px 28px",marginBottom:24}}><div style={{color:"#1e874c",fontSize:12,fontWeight:600,textTransform:"uppercase",letterSpacing:"2px",marginBottom:10}}>İpuçları</div>{unit.ti.map(function(t,i){return <div key={i} style={{fontSize:13,lineHeight:1.6,marginBottom:6,paddingLeft:20,position:"relative"}}><span style={{position:"absolute",left:0,color:"#ffc233"}}>✦</span>{t}</div>})}</div>}
<button onClick={function(){sQ(unit.w,false)}} style={{width:"100%",padding:"14px 0",borderRadius:8,border:"none",background:"#121217",color:"#fff",fontSize:14,fontWeight:500,cursor:"pointer"}}>Bu Konuyu Test Et →</button>
</div>}

{vw==="reading"&&rd&&<div style={{maxWidth:600,margin:"0 auto",padding:"24px 16px 40px",animation:"fadeUp 0.5s ease"}}>
<button onClick={goH} style={{background:"#fff",border:"1px solid #d1d1db",color:"#6c6c89",fontSize:13,cursor:"pointer",padding:"8px 16px",borderRadius:8,marginBottom:24}}>← Geri</button>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><h2 style={{fontSize:24,fontWeight:800}}>{rd.t}</h2><span style={{background:"#e5b5fe",color:"#5423e7",fontSize:11,fontWeight:600,padding:"3px 12px",borderRadius:40}}>{rd.l}</span></div>
<div style={{background:"#fff",borderRadius:32,padding:"28px 32px",marginBottom:24,border:"1px solid #d1d1db",lineHeight:1.85,fontSize:15}}>{rd.p.split("\n\n").map(function(p,i){return <p key={i} style={{marginBottom:16}}>{p}</p>})}</div>
<div style={{background:"#fff",borderRadius:32,padding:"24px 28px",marginBottom:24,border:"1px solid #d1d1db"}}><div style={{color:"#6c6c89",fontSize:12,fontWeight:600,textTransform:"uppercase",letterSpacing:"2px",marginBottom:12}}>Anahtar Kelimeler</div>{rd.w.map(function(w,i){return <div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:i<rd.w.length-1?"1px solid #f7f7f8":"none"}}><span style={{fontSize:14,fontWeight:600}}>{w.e}</span><span style={{fontSize:12,color:"#5423e7",fontWeight:500,background:"#e5b5fe33",padding:"2px 10px",borderRadius:16}}>{w.t}</span></div>})}</div>
<button onClick={function(){sQ(rd.q,true)}} style={{width:"100%",padding:"14px 0",borderRadius:8,border:"none",background:"#121217",color:"#fff",fontSize:14,fontWeight:500,cursor:"pointer"}}>Anlama Quizi →</button>
</div>}

{vw==="quiz"&&<div style={{maxWidth:600,margin:"0 auto",padding:"24px 16px 40px",animation:"fadeUp 0.5s ease"}}>
<button onClick={goH} style={{background:"#fff",border:"1px solid #d1d1db",color:"#6c6c89",fontSize:13,cursor:"pointer",padding:"8px 16px",borderRadius:8,marginBottom:20}}>← Geri</button>
{!dn?(qqs[qi]?<div>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{color:"#6c6c89",fontSize:13}}>Soru {qi+1}/{qqs.length}</span><span style={{color:"#5423e7",fontSize:13,fontWeight:600}}>Puan: {sc}</span></div>
<div style={{height:5,background:"#f7f7f8",borderRadius:3,marginBottom:24,overflow:"hidden"}}><div style={{height:5,background:"linear-gradient(90deg,#5423e7,#cf75ff)",borderRadius:3,width:((qi+1)/qqs.length*100)+"%",transition:"width 0.4s"}}/></div>
<div style={{background:"#fff",borderRadius:32,padding:"28px 32px",marginBottom:16,border:"1px solid #d1d1db"}}>
<h3 style={{fontSize:18,fontWeight:600,lineHeight:1.4,marginBottom:20}}>{qqs[qi].q}</h3>
<div style={{display:"grid",gap:8}}>
{qqs[qi].o.map(function(o,oi){var bg="#f7f7f8",bd="2px solid transparent",co="#121217",lB="transparent",lC="#6c6c89",lD="2px solid #d1d1db",lt=String.fromCharCode(65+oi);if(an){if(oi===qqs[qi].c){bg="#eefbf3";bd="2px solid #1e874c";co="#1e874c";lB="#1e874c";lC="#fff";lD="2px solid #1e874c";lt="✓"}else if(oi===sl){bg="#fef2f2";bd="2px solid #d50b3e";co="#d50b3e";lB="#d50b3e";lC="#fff";lD="2px solid #d50b3e";lt="✗"}}return <button key={oi} onClick={function(){pk(oi)}} style={{display:"flex",alignItems:"center",gap:12,width:"100%",padding:"12px 16px",background:bg,border:bd,borderRadius:10,color:co,fontSize:14,textAlign:"left",cursor:an?"default":"pointer",transition:"all 0.2s"}}><span style={{width:28,height:28,borderRadius:"50%",border:lD,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:600,flexShrink:0,background:lB,color:lC}}>{lt}</span><span>{o}</span></button>})}
</div>
{an&&qqs[qi].x&&<div style={{marginTop:14,padding:"12px 16px",background:"#f7f7f8",borderRadius:10,fontSize:13,color:"#6c6c89",lineHeight:1.6,borderLeft:"3px solid #ffc233"}}>{qqs[qi].x}</div>}
</div>
{an&&<button onClick={nx} style={{width:"100%",padding:"14px 0",border:"none",borderRadius:8,background:"#121217",color:"#fff",fontSize:14,fontWeight:500,cursor:"pointer"}}>{qi+1>=qqs.length?"Sonucu Gör →":"Sonraki →"}</button>}
</div>:<p style={{color:"#6c6c89",textAlign:"center",padding:40}}>Bu konu için yeterli soru yok.</p>):(
<div style={{textAlign:"center",padding:"40px 16px"}}>
<div style={{width:110,height:110,borderRadius:"50%",background:"linear-gradient(135deg,#5423e7,#7047eb)",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 24px",boxShadow:"0 16px 48px rgba(84,35,231,0.25)",animation:"fS 3s ease-in-out infinite"}}><span style={{fontSize:32,color:"#ffc233",fontWeight:700}}>{sc}/{qqs.length}</span></div>
<h3 style={{fontSize:24,fontWeight:700,marginBottom:6}}>{sc>=qqs.length*0.8?"Mükemmel!":sc>=qqs.length*0.5?"İyi!":"Tekrar çalış!"}</h3>
<p style={{color:"#6c6c89",fontSize:15,marginBottom:28}}>{qqs.length} sorudan {sc} doğru</p>
<button onClick={goH} style={{padding:"12px 24px",borderRadius:8,border:"none",background:"#121217",color:"#fff",fontSize:14,fontWeight:500,cursor:"pointer"}}>Konulara Dön</button>
</div>)}
</div>}
</div>)}